//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ArbitrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArbitrationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}CommonFormDataType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CaseFilingAmount" minOccurs="0"/&gt;
 *         &lt;element name="ExplanationOfDispute" type="{http://www.visa.com/ROLSI}DescType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}FirstChargebackCPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}FirstChargebackDisputeAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}FirstChargebackDisputeReasonCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RepresentmentCPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RepresentmentDisputeAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RepresentmentDisputeReasonCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondFirstChargebackCPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondFirstChargebackDisputeAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondFirstChargebackDisputeReasonCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondRepresentmentCPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondRepresentmentDisputeAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondRepresentmentDisputeReasonCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondChargebackCPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondChargebackDisputeAmount" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SecondChargebackDisputeReasonCode" minOccurs="0"/&gt;
 *         &lt;element name="PreArbitrationCPD" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="PreArbitrationDisputeAmount" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="PreArbitrationReasonCode" type="{http://www.visa.com/ROLSI}DisputeReasonCodeType" minOccurs="0"/&gt;
 *         &lt;element name="ArbitrationCPD" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ArbitrationDisputeAmount" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="ArbitrationReasonCode" type="{http://www.visa.com/ROLSI}DisputeReasonCodeType" minOccurs="0"/&gt;
 *         &lt;element name="RetrievalRequestCPD" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="RetrievalRequestReasonCode" type="{http://www.visa.com/ROLSI}DisputeReasonCodeType" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}CaseHistoryGroup"/&gt;
 *         &lt;element name="CaseFilingDateFromPreArbDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CaseFilingDateFromRepreCPD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AppealInd" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}MultiFilingCd" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArbitrationType", propOrder = {
    "caseFilingAmount",
    "explanationOfDispute",
    "firstChargebackCPD",
    "firstChargebackDisputeAmount",
    "firstChargebackDisputeReasonCode",
    "representmentCPD",
    "representmentDisputeAmount",
    "representmentDisputeReasonCode",
    "secondFirstChargebackCPD",
    "secondFirstChargebackDisputeAmount",
    "secondFirstChargebackDisputeReasonCode",
    "secondRepresentmentCPD",
    "secondRepresentmentDisputeAmount",
    "secondRepresentmentDisputeReasonCode",
    "secondChargebackCPD",
    "secondChargebackDisputeAmount",
    "secondChargebackDisputeReasonCode",
    "preArbitrationCPD",
    "preArbitrationDisputeAmount",
    "preArbitrationReasonCode",
    "arbitrationCPD",
    "arbitrationDisputeAmount",
    "arbitrationReasonCode",
    "retrievalRequestCPD",
    "retrievalRequestReasonCode",
    "rfcCpdFromTranCpd",
    "rfcResponseCpdFromRfcCpd",
    "cbCpdFromTranCpd",
    "cbCpdFromRfcCpd",
    "cbCpdFromRfcResponseCpd",
    "repreCpdFromCBCpd",
    "preArbDateFromRepreCpd",
    "secondCBCpdFromRepreCpd",
    "preArbDateFromSecondCBCpd",
    "caseFilingDateFromSecondCBCpd",
    "caseFilingDateFromPreArbDate",
    "caseFilingDateFromRepreCPD",
    "appealInd",
    "multiFilingCd"
})
public class ArbitrationType
    extends CommonFormDataType
{

    @XmlElement(name = "CaseFilingAmount")
    protected AmountType caseFilingAmount;
    @XmlElement(name = "ExplanationOfDispute")
    protected String explanationOfDispute;
    @XmlElement(name = "FirstChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstChargebackCPD;
    @XmlElement(name = "FirstChargebackDisputeAmount")
    protected AmountType firstChargebackDisputeAmount;
    @XmlElement(name = "FirstChargebackDisputeReasonCode")
    protected String firstChargebackDisputeReasonCode;
    @XmlElement(name = "RepresentmentCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar representmentCPD;
    @XmlElement(name = "RepresentmentDisputeAmount")
    protected AmountType representmentDisputeAmount;
    @XmlElement(name = "RepresentmentDisputeReasonCode")
    protected String representmentDisputeReasonCode;
    @XmlElement(name = "SecondFirstChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondFirstChargebackCPD;
    @XmlElement(name = "SecondFirstChargebackDisputeAmount")
    protected AmountType secondFirstChargebackDisputeAmount;
    @XmlElement(name = "SecondFirstChargebackDisputeReasonCode")
    protected String secondFirstChargebackDisputeReasonCode;
    @XmlElement(name = "SecondRepresentmentCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondRepresentmentCPD;
    @XmlElement(name = "SecondRepresentmentDisputeAmount")
    protected AmountType secondRepresentmentDisputeAmount;
    @XmlElement(name = "SecondRepresentmentDisputeReasonCode")
    protected String secondRepresentmentDisputeReasonCode;
    @XmlElement(name = "SecondChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondChargebackCPD;
    @XmlElement(name = "SecondChargebackDisputeAmount")
    protected AmountType secondChargebackDisputeAmount;
    @XmlElement(name = "SecondChargebackDisputeReasonCode")
    protected String secondChargebackDisputeReasonCode;
    @XmlElement(name = "PreArbitrationCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar preArbitrationCPD;
    @XmlElement(name = "PreArbitrationDisputeAmount")
    protected AmountType preArbitrationDisputeAmount;
    @XmlElement(name = "PreArbitrationReasonCode")
    protected String preArbitrationReasonCode;
    @XmlElement(name = "ArbitrationCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar arbitrationCPD;
    @XmlElement(name = "ArbitrationDisputeAmount")
    protected AmountType arbitrationDisputeAmount;
    @XmlElement(name = "ArbitrationReasonCode")
    protected String arbitrationReasonCode;
    @XmlElement(name = "RetrievalRequestCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar retrievalRequestCPD;
    @XmlElement(name = "RetrievalRequestReasonCode")
    protected String retrievalRequestReasonCode;
    @XmlElement(name = "RfcCpdFromTranCpd")
    protected String rfcCpdFromTranCpd;
    @XmlElement(name = "RfcResponseCpdFromRfcCpd")
    protected String rfcResponseCpdFromRfcCpd;
    @XmlElement(name = "CBCpdFromTranCpd")
    protected String cbCpdFromTranCpd;
    @XmlElement(name = "CBCpdFromRfcCpd")
    protected String cbCpdFromRfcCpd;
    @XmlElement(name = "CBCpdFromRfcResponseCpd")
    protected String cbCpdFromRfcResponseCpd;
    @XmlElement(name = "RepreCpdFromCBCpd")
    protected String repreCpdFromCBCpd;
    @XmlElement(name = "PreArbDateFromRepreCpd")
    protected String preArbDateFromRepreCpd;
    @XmlElement(name = "SecondCBCpdFromRepreCpd")
    protected String secondCBCpdFromRepreCpd;
    @XmlElement(name = "PreArbDateFromSecondCBCpd")
    protected String preArbDateFromSecondCBCpd;
    @XmlElement(name = "CaseFilingDateFromSecondCBCpd")
    protected String caseFilingDateFromSecondCBCpd;
    @XmlElement(name = "CaseFilingDateFromPreArbDate")
    protected String caseFilingDateFromPreArbDate;
    @XmlElement(name = "CaseFilingDateFromRepreCPD")
    protected String caseFilingDateFromRepreCPD;
    @XmlElement(name = "AppealInd")
    protected Boolean appealInd;
    @XmlElement(name = "MultiFilingCd")
    protected String multiFilingCd;

    /**
     * Gets the value of the caseFilingAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getCaseFilingAmount() {
        return caseFilingAmount;
    }

    /**
     * Sets the value of the caseFilingAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setCaseFilingAmount(AmountType value) {
        this.caseFilingAmount = value;
    }

    /**
     * Gets the value of the explanationOfDispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplanationOfDispute() {
        return explanationOfDispute;
    }

    /**
     * Sets the value of the explanationOfDispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplanationOfDispute(String value) {
        this.explanationOfDispute = value;
    }

    /**
     * Gets the value of the firstChargebackCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstChargebackCPD() {
        return firstChargebackCPD;
    }

    /**
     * Sets the value of the firstChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstChargebackCPD(XMLGregorianCalendar value) {
        this.firstChargebackCPD = value;
    }

    /**
     * Gets the value of the firstChargebackDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFirstChargebackDisputeAmount() {
        return firstChargebackDisputeAmount;
    }

    /**
     * Sets the value of the firstChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFirstChargebackDisputeAmount(AmountType value) {
        this.firstChargebackDisputeAmount = value;
    }

    /**
     * Gets the value of the firstChargebackDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstChargebackDisputeReasonCode() {
        return firstChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the firstChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstChargebackDisputeReasonCode(String value) {
        this.firstChargebackDisputeReasonCode = value;
    }

    /**
     * Gets the value of the representmentCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRepresentmentCPD() {
        return representmentCPD;
    }

    /**
     * Sets the value of the representmentCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRepresentmentCPD(XMLGregorianCalendar value) {
        this.representmentCPD = value;
    }

    /**
     * Gets the value of the representmentDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getRepresentmentDisputeAmount() {
        return representmentDisputeAmount;
    }

    /**
     * Sets the value of the representmentDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setRepresentmentDisputeAmount(AmountType value) {
        this.representmentDisputeAmount = value;
    }

    /**
     * Gets the value of the representmentDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentmentDisputeReasonCode() {
        return representmentDisputeReasonCode;
    }

    /**
     * Sets the value of the representmentDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentmentDisputeReasonCode(String value) {
        this.representmentDisputeReasonCode = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondFirstChargebackCPD() {
        return secondFirstChargebackCPD;
    }

    /**
     * Sets the value of the secondFirstChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondFirstChargebackCPD(XMLGregorianCalendar value) {
        this.secondFirstChargebackCPD = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondFirstChargebackDisputeAmount() {
        return secondFirstChargebackDisputeAmount;
    }

    /**
     * Sets the value of the secondFirstChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondFirstChargebackDisputeAmount(AmountType value) {
        this.secondFirstChargebackDisputeAmount = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondFirstChargebackDisputeReasonCode() {
        return secondFirstChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the secondFirstChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondFirstChargebackDisputeReasonCode(String value) {
        this.secondFirstChargebackDisputeReasonCode = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondRepresentmentCPD() {
        return secondRepresentmentCPD;
    }

    /**
     * Sets the value of the secondRepresentmentCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondRepresentmentCPD(XMLGregorianCalendar value) {
        this.secondRepresentmentCPD = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondRepresentmentDisputeAmount() {
        return secondRepresentmentDisputeAmount;
    }

    /**
     * Sets the value of the secondRepresentmentDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondRepresentmentDisputeAmount(AmountType value) {
        this.secondRepresentmentDisputeAmount = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondRepresentmentDisputeReasonCode() {
        return secondRepresentmentDisputeReasonCode;
    }

    /**
     * Sets the value of the secondRepresentmentDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondRepresentmentDisputeReasonCode(String value) {
        this.secondRepresentmentDisputeReasonCode = value;
    }

    /**
     * Gets the value of the secondChargebackCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondChargebackCPD() {
        return secondChargebackCPD;
    }

    /**
     * Sets the value of the secondChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondChargebackCPD(XMLGregorianCalendar value) {
        this.secondChargebackCPD = value;
    }

    /**
     * Gets the value of the secondChargebackDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondChargebackDisputeAmount() {
        return secondChargebackDisputeAmount;
    }

    /**
     * Sets the value of the secondChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondChargebackDisputeAmount(AmountType value) {
        this.secondChargebackDisputeAmount = value;
    }

    /**
     * Gets the value of the secondChargebackDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondChargebackDisputeReasonCode() {
        return secondChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the secondChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondChargebackDisputeReasonCode(String value) {
        this.secondChargebackDisputeReasonCode = value;
    }

    /**
     * Gets the value of the preArbitrationCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPreArbitrationCPD() {
        return preArbitrationCPD;
    }

    /**
     * Sets the value of the preArbitrationCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreArbitrationCPD(XMLGregorianCalendar value) {
        this.preArbitrationCPD = value;
    }

    /**
     * Gets the value of the preArbitrationDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getPreArbitrationDisputeAmount() {
        return preArbitrationDisputeAmount;
    }

    /**
     * Sets the value of the preArbitrationDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPreArbitrationDisputeAmount(AmountType value) {
        this.preArbitrationDisputeAmount = value;
    }

    /**
     * Gets the value of the preArbitrationReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbitrationReasonCode() {
        return preArbitrationReasonCode;
    }

    /**
     * Sets the value of the preArbitrationReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbitrationReasonCode(String value) {
        this.preArbitrationReasonCode = value;
    }

    /**
     * Gets the value of the arbitrationCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArbitrationCPD() {
        return arbitrationCPD;
    }

    /**
     * Sets the value of the arbitrationCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArbitrationCPD(XMLGregorianCalendar value) {
        this.arbitrationCPD = value;
    }

    /**
     * Gets the value of the arbitrationDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getArbitrationDisputeAmount() {
        return arbitrationDisputeAmount;
    }

    /**
     * Sets the value of the arbitrationDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setArbitrationDisputeAmount(AmountType value) {
        this.arbitrationDisputeAmount = value;
    }

    /**
     * Gets the value of the arbitrationReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArbitrationReasonCode() {
        return arbitrationReasonCode;
    }

    /**
     * Sets the value of the arbitrationReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArbitrationReasonCode(String value) {
        this.arbitrationReasonCode = value;
    }

    /**
     * Gets the value of the retrievalRequestCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRetrievalRequestCPD() {
        return retrievalRequestCPD;
    }

    /**
     * Sets the value of the retrievalRequestCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRetrievalRequestCPD(XMLGregorianCalendar value) {
        this.retrievalRequestCPD = value;
    }

    /**
     * Gets the value of the retrievalRequestReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievalRequestReasonCode() {
        return retrievalRequestReasonCode;
    }

    /**
     * Sets the value of the retrievalRequestReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievalRequestReasonCode(String value) {
        this.retrievalRequestReasonCode = value;
    }

    /**
     * Gets the value of the rfcCpdFromTranCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcCpdFromTranCpd() {
        return rfcCpdFromTranCpd;
    }

    /**
     * Sets the value of the rfcCpdFromTranCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcCpdFromTranCpd(String value) {
        this.rfcCpdFromTranCpd = value;
    }

    /**
     * Gets the value of the rfcResponseCpdFromRfcCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcResponseCpdFromRfcCpd() {
        return rfcResponseCpdFromRfcCpd;
    }

    /**
     * Sets the value of the rfcResponseCpdFromRfcCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcResponseCpdFromRfcCpd(String value) {
        this.rfcResponseCpdFromRfcCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromTranCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromTranCpd() {
        return cbCpdFromTranCpd;
    }

    /**
     * Sets the value of the cbCpdFromTranCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromTranCpd(String value) {
        this.cbCpdFromTranCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromRfcCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromRfcCpd() {
        return cbCpdFromRfcCpd;
    }

    /**
     * Sets the value of the cbCpdFromRfcCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromRfcCpd(String value) {
        this.cbCpdFromRfcCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromRfcResponseCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromRfcResponseCpd() {
        return cbCpdFromRfcResponseCpd;
    }

    /**
     * Sets the value of the cbCpdFromRfcResponseCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromRfcResponseCpd(String value) {
        this.cbCpdFromRfcResponseCpd = value;
    }

    /**
     * Gets the value of the repreCpdFromCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepreCpdFromCBCpd() {
        return repreCpdFromCBCpd;
    }

    /**
     * Sets the value of the repreCpdFromCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepreCpdFromCBCpd(String value) {
        this.repreCpdFromCBCpd = value;
    }

    /**
     * Gets the value of the preArbDateFromRepreCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbDateFromRepreCpd() {
        return preArbDateFromRepreCpd;
    }

    /**
     * Sets the value of the preArbDateFromRepreCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbDateFromRepreCpd(String value) {
        this.preArbDateFromRepreCpd = value;
    }

    /**
     * Gets the value of the secondCBCpdFromRepreCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondCBCpdFromRepreCpd() {
        return secondCBCpdFromRepreCpd;
    }

    /**
     * Sets the value of the secondCBCpdFromRepreCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondCBCpdFromRepreCpd(String value) {
        this.secondCBCpdFromRepreCpd = value;
    }

    /**
     * Gets the value of the preArbDateFromSecondCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbDateFromSecondCBCpd() {
        return preArbDateFromSecondCBCpd;
    }

    /**
     * Sets the value of the preArbDateFromSecondCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbDateFromSecondCBCpd(String value) {
        this.preArbDateFromSecondCBCpd = value;
    }

    /**
     * Gets the value of the caseFilingDateFromSecondCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseFilingDateFromSecondCBCpd() {
        return caseFilingDateFromSecondCBCpd;
    }

    /**
     * Sets the value of the caseFilingDateFromSecondCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseFilingDateFromSecondCBCpd(String value) {
        this.caseFilingDateFromSecondCBCpd = value;
    }

    /**
     * Gets the value of the caseFilingDateFromPreArbDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseFilingDateFromPreArbDate() {
        return caseFilingDateFromPreArbDate;
    }

    /**
     * Sets the value of the caseFilingDateFromPreArbDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseFilingDateFromPreArbDate(String value) {
        this.caseFilingDateFromPreArbDate = value;
    }

    /**
     * Gets the value of the caseFilingDateFromRepreCPD property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseFilingDateFromRepreCPD() {
        return caseFilingDateFromRepreCPD;
    }

    /**
     * Sets the value of the caseFilingDateFromRepreCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseFilingDateFromRepreCPD(String value) {
        this.caseFilingDateFromRepreCPD = value;
    }

    /**
     * Gets the value of the appealInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAppealInd() {
        return appealInd;
    }

    /**
     * Sets the value of the appealInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAppealInd(Boolean value) {
        this.appealInd = value;
    }

    /**
     * Gets the value of the multiFilingCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultiFilingCd() {
        return multiFilingCd;
    }

    /**
     * Sets the value of the multiFilingCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultiFilingCd(String value) {
        this.multiFilingCd = value;
    }

}
