//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TranHeaderInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TranHeaderInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}AccountNumber" minOccurs="0"/&gt;
 *           &lt;group ref="{http://www.visa.com/ROLSI}PANlessFieldGroup" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}Token" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TokenAssuranceLevel" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}OnUsAffiliation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}Transaction" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}MerchantGroup"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}ARN" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}ECMOTO" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}ReimbursementAttribute" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SpecialConditionInd" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CPD" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionCategory" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AcquirerBID" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}NetworkID" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AcquirerBIN" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RetrievalReferenceNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SystemTraceAuditNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CardholderName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TranDestAmt" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}ProcessingCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}IssuerName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AcquirerName" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AccountType" minOccurs="0"/&gt;
 *         &lt;element name="AccountType1Identification" type="{http://www.visa.com/ROLSI}AccountType1IdentificationType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}DCCInd" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}DCCIndDescription" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}DomesticProcessingInd" minOccurs="0"/&gt;
 *         &lt;element name="DisputeJurisdiction" type="{http://www.visa.com/ROLSI}JurisdictionType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}BusinessAppId" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TranHeaderInfoType", propOrder = {
    "accountNumber",
    "trn",
    "consumerAccountNumber",
    "checkNumber",
    "token",
    "tokenAssuranceLevel",
    "onUsAffiliation",
    "transaction",
    "merchantName",
    "merchantCity",
    "merchantCountrySubEntityCode",
    "merchantCountryCode",
    "merchantPostalCode",
    "mcc",
    "arn",
    "ecmoto",
    "reimbursementAttribute",
    "specialConditionInd",
    "cpd",
    "transactionCategory",
    "acquirerBID",
    "networkID",
    "acquirerBIN",
    "retrievalReferenceNumber",
    "systemTraceAuditNumber",
    "cardholderName",
    "tranDestAmt",
    "processingCode",
    "issuerName",
    "acquirerName",
    "accountType",
    "accountType1Identification",
    "dccInd",
    "dccIndDescription",
    "domesticProcessingInd",
    "disputeJurisdiction",
    "businessAppId"
})
@XmlSeeAlso({
    AdjustmentTransactionInfoType.class,
    CreateCaseTransactionType.class,
    QnTransactionInfoType.class
})
public class TranHeaderInfoType {

    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "TRN")
    protected String trn;
    @XmlElement(name = "ConsumerAccountNumber")
    protected String consumerAccountNumber;
    @XmlElement(name = "CheckNumber")
    protected String checkNumber;
    @XmlElement(name = "Token")
    protected String token;
    @XmlElement(name = "TokenAssuranceLevel")
    protected String tokenAssuranceLevel;
    @XmlElement(name = "OnUsAffiliation")
    protected String onUsAffiliation;
    @XmlElement(name = "Transaction")
    protected TransactionType transaction;
    @XmlElement(name = "MerchantName")
    protected String merchantName;
    @XmlElement(name = "MerchantCity")
    protected String merchantCity;
    @XmlElement(name = "MerchantCountrySubEntityCode")
    protected String merchantCountrySubEntityCode;
    @XmlElement(name = "MerchantCountryCode")
    protected String merchantCountryCode;
    @XmlElement(name = "MerchantPostalCode")
    protected String merchantPostalCode;
    @XmlElement(name = "MCC")
    protected String mcc;
    @XmlElement(name = "ARN")
    protected String arn;
    @XmlElement(name = "ECMOTO")
    protected String ecmoto;
    @XmlElement(name = "ReimbursementAttribute")
    protected String reimbursementAttribute;
    @XmlElement(name = "SpecialConditionInd")
    protected String specialConditionInd;
    @XmlElement(name = "CPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cpd;
    @XmlElement(name = "TransactionCategory")
    @XmlSchemaType(name = "string")
    protected ManualTranCatType transactionCategory;
    @XmlElement(name = "AcquirerBID")
    protected String acquirerBID;
    @XmlElement(name = "NetworkID")
    protected String networkID;
    @XmlElement(name = "AcquirerBIN")
    protected String acquirerBIN;
    @XmlElement(name = "RetrievalReferenceNumber")
    protected String retrievalReferenceNumber;
    @XmlElement(name = "SystemTraceAuditNumber")
    protected String systemTraceAuditNumber;
    @XmlElement(name = "CardholderName")
    protected String cardholderName;
    @XmlElement(name = "TranDestAmt")
    protected AmountType tranDestAmt;
    @XmlElement(name = "ProcessingCode")
    protected String processingCode;
    @XmlElement(name = "IssuerName")
    protected String issuerName;
    @XmlElement(name = "AcquirerName")
    protected String acquirerName;
    @XmlElement(name = "AccountType")
    protected String accountType;
    @XmlElement(name = "AccountType1Identification")
    protected String accountType1Identification;
    @XmlElement(name = "DCCInd")
    protected String dccInd;
    @XmlElement(name = "DCCIndDescription")
    protected String dccIndDescription;
    @XmlElement(name = "DomesticProcessingInd")
    protected Boolean domesticProcessingInd;
    @XmlElement(name = "DisputeJurisdiction")
    protected JurisdictionType disputeJurisdiction;
    @XmlElement(name = "BusinessAppId")
    protected String businessAppId;

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the trn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRN() {
        return trn;
    }

    /**
     * Sets the value of the trn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRN(String value) {
        this.trn = value;
    }

    /**
     * Gets the value of the consumerAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsumerAccountNumber() {
        return consumerAccountNumber;
    }

    /**
     * Sets the value of the consumerAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsumerAccountNumber(String value) {
        this.consumerAccountNumber = value;
    }

    /**
     * Gets the value of the checkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCheckNumber() {
        return checkNumber;
    }

    /**
     * Sets the value of the checkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCheckNumber(String value) {
        this.checkNumber = value;
    }

    /**
     * Gets the value of the token property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToken() {
        return token;
    }

    /**
     * Sets the value of the token property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToken(String value) {
        this.token = value;
    }

    /**
     * Gets the value of the tokenAssuranceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTokenAssuranceLevel() {
        return tokenAssuranceLevel;
    }

    /**
     * Sets the value of the tokenAssuranceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTokenAssuranceLevel(String value) {
        this.tokenAssuranceLevel = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnUsAffiliation() {
        return onUsAffiliation;
    }

    /**
     * Sets the value of the onUsAffiliation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnUsAffiliation(String value) {
        this.onUsAffiliation = value;
    }

    /**
     * Gets the value of the transaction property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransaction() {
        return transaction;
    }

    /**
     * Sets the value of the transaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransaction(TransactionType value) {
        this.transaction = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantName(String value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the merchantCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCity() {
        return merchantCity;
    }

    /**
     * Sets the value of the merchantCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCity(String value) {
        this.merchantCity = value;
    }

    /**
     * Gets the value of the merchantCountrySubEntityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCountrySubEntityCode() {
        return merchantCountrySubEntityCode;
    }

    /**
     * Sets the value of the merchantCountrySubEntityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCountrySubEntityCode(String value) {
        this.merchantCountrySubEntityCode = value;
    }

    /**
     * Gets the value of the merchantCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCountryCode() {
        return merchantCountryCode;
    }

    /**
     * Sets the value of the merchantCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCountryCode(String value) {
        this.merchantCountryCode = value;
    }

    /**
     * Gets the value of the merchantPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantPostalCode() {
        return merchantPostalCode;
    }

    /**
     * Sets the value of the merchantPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantPostalCode(String value) {
        this.merchantPostalCode = value;
    }

    /**
     * Gets the value of the mcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCC() {
        return mcc;
    }

    /**
     * Sets the value of the mcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCC(String value) {
        this.mcc = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARN(String value) {
        this.arn = value;
    }

    /**
     * Gets the value of the ecmoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECMOTO() {
        return ecmoto;
    }

    /**
     * Sets the value of the ecmoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECMOTO(String value) {
        this.ecmoto = value;
    }

    /**
     * Gets the value of the reimbursementAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReimbursementAttribute() {
        return reimbursementAttribute;
    }

    /**
     * Sets the value of the reimbursementAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReimbursementAttribute(String value) {
        this.reimbursementAttribute = value;
    }

    /**
     * Gets the value of the specialConditionInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialConditionInd() {
        return specialConditionInd;
    }

    /**
     * Sets the value of the specialConditionInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialConditionInd(String value) {
        this.specialConditionInd = value;
    }

    /**
     * Gets the value of the cpd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCPD() {
        return cpd;
    }

    /**
     * Sets the value of the cpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCPD(XMLGregorianCalendar value) {
        this.cpd = value;
    }

    /**
     * Gets the value of the transactionCategory property.
     * 
     * @return
     *     possible object is
     *     {@link ManualTranCatType }
     *     
     */
    public ManualTranCatType getTransactionCategory() {
        return transactionCategory;
    }

    /**
     * Sets the value of the transactionCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManualTranCatType }
     *     
     */
    public void setTransactionCategory(ManualTranCatType value) {
        this.transactionCategory = value;
    }

    /**
     * Gets the value of the acquirerBID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerBID() {
        return acquirerBID;
    }

    /**
     * Sets the value of the acquirerBID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerBID(String value) {
        this.acquirerBID = value;
    }

    /**
     * Gets the value of the networkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkID() {
        return networkID;
    }

    /**
     * Sets the value of the networkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkID(String value) {
        this.networkID = value;
    }

    /**
     * Gets the value of the acquirerBIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerBIN() {
        return acquirerBIN;
    }

    /**
     * Sets the value of the acquirerBIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerBIN(String value) {
        this.acquirerBIN = value;
    }

    /**
     * Gets the value of the retrievalReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievalReferenceNumber() {
        return retrievalReferenceNumber;
    }

    /**
     * Sets the value of the retrievalReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievalReferenceNumber(String value) {
        this.retrievalReferenceNumber = value;
    }

    /**
     * Gets the value of the systemTraceAuditNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemTraceAuditNumber() {
        return systemTraceAuditNumber;
    }

    /**
     * Sets the value of the systemTraceAuditNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemTraceAuditNumber(String value) {
        this.systemTraceAuditNumber = value;
    }

    /**
     * Gets the value of the cardholderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderName() {
        return cardholderName;
    }

    /**
     * Sets the value of the cardholderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderName(String value) {
        this.cardholderName = value;
    }

    /**
     * @direction: Response
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getTranDestAmt() {
        return tranDestAmt;
    }

    /**
     * Sets the value of the tranDestAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setTranDestAmt(AmountType value) {
        this.tranDestAmt = value;
    }

    /**
     * Gets the value of the processingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingCode() {
        return processingCode;
    }

    /**
     * Sets the value of the processingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingCode(String value) {
        this.processingCode = value;
    }

    /**
     * Gets the value of the issuerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerName() {
        return issuerName;
    }

    /**
     * Sets the value of the issuerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerName(String value) {
        this.issuerName = value;
    }

    /**
     * Gets the value of the acquirerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerName() {
        return acquirerName;
    }

    /**
     * Sets the value of the acquirerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerName(String value) {
        this.acquirerName = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountType1Identification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType1Identification() {
        return accountType1Identification;
    }

    /**
     * Sets the value of the accountType1Identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType1Identification(String value) {
        this.accountType1Identification = value;
    }

    /**
     * Gets the value of the dccInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCCInd() {
        return dccInd;
    }

    /**
     * Sets the value of the dccInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCCInd(String value) {
        this.dccInd = value;
    }

    /**
     * Gets the value of the dccIndDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCCIndDescription() {
        return dccIndDescription;
    }

    /**
     * Sets the value of the dccIndDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCCIndDescription(String value) {
        this.dccIndDescription = value;
    }

    /**
     * Gets the value of the domesticProcessingInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDomesticProcessingInd() {
        return domesticProcessingInd;
    }

    /**
     * Sets the value of the domesticProcessingInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDomesticProcessingInd(Boolean value) {
        this.domesticProcessingInd = value;
    }

    /**
     * Gets the value of the disputeJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link JurisdictionType }
     *     
     */
    public JurisdictionType getDisputeJurisdiction() {
        return disputeJurisdiction;
    }

    /**
     * Sets the value of the disputeJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JurisdictionType }
     *     
     */
    public void setDisputeJurisdiction(JurisdictionType value) {
        this.disputeJurisdiction = value;
    }

    /**
     * Gets the value of the businessAppId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessAppId() {
        return businessAppId;
    }

    /**
     * Sets the value of the businessAppId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessAppId(String value) {
        this.businessAppId = value;
    }

}
