//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * @direction: Response
 * 
 * <p>Java class for AdjustmentResponseDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdjustmentResponseDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AdditionalTransactionInfo" type="{http://www.visa.com/ROLSI}AdditionalTransactionInfoType" minOccurs="0"/&gt;
 *         &lt;element name="Adjustment" type="{http://www.visa.com/ROLSI}AdjustmentResponseType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SwitchingSystemStatus" maxOccurs="6" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdjustmentResponseDataType", propOrder = {
    "additionalTransactionInfo",
    "adjustment",
    "switchingSystemStatus"
})
public class AdjustmentResponseDataType {

    @XmlElement(name = "AdditionalTransactionInfo")
    protected AdditionalTransactionInfoType additionalTransactionInfo;
    @XmlElement(name = "Adjustment")
    protected AdjustmentResponseType adjustment;
    @XmlElement(name = "SwitchingSystemStatus")
    protected List<SwitchingSystemStatusType> switchingSystemStatus;

    /**
     * Gets the value of the additionalTransactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalTransactionInfoType }
     *     
     */
    public AdditionalTransactionInfoType getAdditionalTransactionInfo() {
        return additionalTransactionInfo;
    }

    /**
     * Sets the value of the additionalTransactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalTransactionInfoType }
     *     
     */
    public void setAdditionalTransactionInfo(AdditionalTransactionInfoType value) {
        this.additionalTransactionInfo = value;
    }

    /**
     * Gets the value of the adjustment property.
     * 
     * @return
     *     possible object is
     *     {@link AdjustmentResponseType }
     *     
     */
    public AdjustmentResponseType getAdjustment() {
        return adjustment;
    }

    /**
     * Sets the value of the adjustment property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdjustmentResponseType }
     *     
     */
    public void setAdjustment(AdjustmentResponseType value) {
        this.adjustment = value;
    }

    /**
     * Gets the value of the switchingSystemStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the switchingSystemStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwitchingSystemStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SwitchingSystemStatusType }
     * 
     * 
     */
    public List<SwitchingSystemStatusType> getSwitchingSystemStatus() {
        if (switchingSystemStatus == null) {
            switchingSystemStatus = new ArrayList<SwitchingSystemStatusType>();
        }
        return this.switchingSystemStatus;
    }

}
