//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RTAdditionalFinInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RTAdditionalFinInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}AdditionalFnInfoType"&gt;
 *       &lt;attribute name="createFinancial" type="{http://www.visa.com/ROLSI}YNOType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RTAdditionalFinInfoType")
public class RTAdditionalFinInfoType
    extends AdditionalFnInfoType
{

    @XmlAttribute(name = "createFinancial")
    protected YNOType createFinancial;

    /**
     * Gets the value of the createFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link YNOType }
     *     
     */
    public YNOType getCreateFinancial() {
        return createFinancial;
    }

    /**
     * Sets the value of the createFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNOType }
     *     
     */
    public void setCreateFinancial(YNOType value) {
        this.createFinancial = value;
    }

}
