//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManualCaseCreationRequestBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManualCaseCreationRequestBodyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}RequestBodyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ManualCaseCreationRequest" type="{http://www.visa.com/ROLSI}RTSIManualCaseCreationType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManualCaseCreationRequestBodyType", propOrder = {
    "manualCaseCreationRequest"
})
public class ManualCaseCreationRequestBodyType
    extends RequestBodyType
{

    @XmlElement(name = "ManualCaseCreationRequest", required = true)
    protected RTSIManualCaseCreationType manualCaseCreationRequest;

    /**
     * Gets the value of the manualCaseCreationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIManualCaseCreationType }
     *     
     */
    public RTSIManualCaseCreationType getManualCaseCreationRequest() {
        return manualCaseCreationRequest;
    }

    /**
     * Sets the value of the manualCaseCreationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIManualCaseCreationType }
     *     
     */
    public void setManualCaseCreationRequest(RTSIManualCaseCreationType value) {
        this.manualCaseCreationRequest = value;
    }

}
