//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetDisputePreArbResponseDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetDisputePreArbResponseDetailsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionInfo" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}VisaCaseNumber" minOccurs="0"/&gt;
 *         &lt;element name="DisputePreArbResponseId" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AssociatedTransGroupId" minOccurs="0"/&gt;
 *         &lt;element name="ATRSelectionReqdInd" type="{http://www.visa.com/ROLSI}ATRSelectionReqdIndType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}MemberCaseNumber" minOccurs="0"/&gt;
 *         &lt;element name="DisputeCategoryCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CreateDisputeFinancial" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionMessageFormat" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}GetDisputePreArbResponseDetails" minOccurs="0"/&gt;
 *         &lt;element name="DisputeAsImageResponseDescriptor" type="{http://www.visa.com/ROLSI}DisputeAsImageResponseDescriptorType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetDisputePreArbResponseDetailsResponseType", propOrder = {
    "transactionInfo",
    "visaCaseNumber",
    "disputePreArbResponseId",
    "associatedTransGroupId",
    "atrSelectionReqdInd",
    "memberCaseNumber",
    "disputeCategoryCondition",
    "createDisputeFinancial",
    "transactionMessageFormat",
    "questionnaireRecalledDate",
    "domProcQualifiedCaseInd",
    "disputeCategory",
    "disputeCondition",
    "disputeCardholderInfo",
    "merchantContactInfo",
    "disputeHistorySummary",
    "note",
    "caseHistorySummary",
    "preArbResponse",
    "acceptanceAmount",
    "providingNewInfoInd",
    "newInformationDetails",
    "liabilityNotAcceptedFully",
    "issuerCertifiesCardholderCompEvidence",
    "cardholderNameAddressNotMatchInd",
    "cardholderContinuesDispute",
    "explainContinuingDispute",
    "cardholderRequiresATMRecordInd",
    "atmRecordRequiredForLegalInd",
    "explainATMRecordRequiredForLegal",
    "issuerAcquirerContactInfo",
    "recallInd",
    "recallReason",
    "disputeImageAttachment",
    "disputeAsImageResponseDescriptor"
})
public class GetDisputePreArbResponseDetailsResponseType {

    @XmlElement(name = "TransactionInfo")
    protected TranHeaderInfoType transactionInfo;
    @XmlElement(name = "VisaCaseNumber")
    protected Long visaCaseNumber;
    @XmlElement(name = "DisputePreArbResponseId")
    protected Long disputePreArbResponseId;
    @XmlElement(name = "AssociatedTransGroupId")
    protected Long associatedTransGroupId;
    @XmlElement(name = "ATRSelectionReqdInd")
    @XmlSchemaType(name = "string")
    protected ATRSelectionReqdIndType atrSelectionReqdInd;
    @XmlElement(name = "MemberCaseNumber")
    protected String memberCaseNumber;
    @XmlElement(name = "DisputeCategoryCondition")
    protected String disputeCategoryCondition;
    @XmlElement(name = "CreateDisputeFinancial")
    @XmlSchemaType(name = "string")
    protected YNType createDisputeFinancial;
    @XmlElement(name = "TransactionMessageFormat")
    protected String transactionMessageFormat;
    @XmlElement(name = "QuestionnaireRecalledDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar questionnaireRecalledDate;
    @XmlElement(name = "DomProcQualifiedCaseInd")
    protected Boolean domProcQualifiedCaseInd;
    @XmlElement(name = "DisputeCategory")
    protected DisputeCategoryType disputeCategory;
    @XmlElement(name = "DisputeCondition")
    protected String disputeCondition;
    @XmlElement(name = "DisputeCardholderInfo")
    protected DisputeCardholderInfoType disputeCardholderInfo;
    @XmlElement(name = "MerchantContactInfo")
    protected MerchantContactInfoType merchantContactInfo;
    @XmlElement(name = "DisputeHistorySummary")
    protected DisputeHistorySummaryType disputeHistorySummary;
    @XmlElement(name = "Note")
    protected String note;
    @XmlElement(name = "CaseHistorySummary")
    protected CaseHistorySummaryType caseHistorySummary;
    @XmlElement(name = "PreArbResponse")
    @XmlSchemaType(name = "string")
    protected DisputeResponseType preArbResponse;
    @XmlElement(name = "AcceptanceAmount")
    protected AmountType acceptanceAmount;
    @XmlElement(name = "ProvidingNewInfoInd")
    @XmlSchemaType(name = "string")
    protected YNType providingNewInfoInd;
    @XmlElement(name = "NewInformationDetails")
    protected String newInformationDetails;
    @XmlElement(name = "LiabilityNotAcceptedFully")
    protected String liabilityNotAcceptedFully;
    @XmlElement(name = "IssuerCertifiesCardholderCompEvidence")
    @XmlSchemaType(name = "string")
    protected YNType issuerCertifiesCardholderCompEvidence;
    @XmlElement(name = "CardholderNameAddressNotMatchInd")
    @XmlSchemaType(name = "string")
    protected YNType cardholderNameAddressNotMatchInd;
    @XmlElement(name = "CardholderContinuesDispute")
    protected String cardholderContinuesDispute;
    @XmlElement(name = "ExplainContinuingDispute")
    protected String explainContinuingDispute;
    @XmlElement(name = "CardholderRequiresATMRecordInd")
    protected Boolean cardholderRequiresATMRecordInd;
    @XmlElement(name = "ATMRecordRequiredForLegalInd")
    protected Boolean atmRecordRequiredForLegalInd;
    @XmlElement(name = "ExplainATMRecordRequiredForLegal")
    protected String explainATMRecordRequiredForLegal;
    @XmlElement(name = "IssuerAcquirerContactInfo")
    protected IssuerAcquirerContactInfoType issuerAcquirerContactInfo;
    @XmlElement(name = "RecallInd")
    protected Boolean recallInd;
    @XmlElement(name = "RecallReason")
    protected String recallReason;
    @XmlElement(name = "DisputeImageAttachment")
    protected DisputeAttachmentDescriptorType disputeImageAttachment;
    @XmlElement(name = "DisputeAsImageResponseDescriptor")
    protected DisputeAsImageResponseDescriptorType disputeAsImageResponseDescriptor;

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TranHeaderInfoType }
     *     
     */
    public TranHeaderInfoType getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranHeaderInfoType }
     *     
     */
    public void setTransactionInfo(TranHeaderInfoType value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the visaCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVisaCaseNumber() {
        return visaCaseNumber;
    }

    /**
     * Sets the value of the visaCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVisaCaseNumber(Long value) {
        this.visaCaseNumber = value;
    }

    /**
     * Gets the value of the disputePreArbResponseId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDisputePreArbResponseId() {
        return disputePreArbResponseId;
    }

    /**
     * Sets the value of the disputePreArbResponseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDisputePreArbResponseId(Long value) {
        this.disputePreArbResponseId = value;
    }

    /**
     * Gets the value of the associatedTransGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAssociatedTransGroupId() {
        return associatedTransGroupId;
    }

    /**
     * Sets the value of the associatedTransGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAssociatedTransGroupId(Long value) {
        this.associatedTransGroupId = value;
    }

    /**
     * Gets the value of the atrSelectionReqdInd property.
     * 
     * @return
     *     possible object is
     *     {@link ATRSelectionReqdIndType }
     *     
     */
    public ATRSelectionReqdIndType getATRSelectionReqdInd() {
        return atrSelectionReqdInd;
    }

    /**
     * Sets the value of the atrSelectionReqdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATRSelectionReqdIndType }
     *     
     */
    public void setATRSelectionReqdInd(ATRSelectionReqdIndType value) {
        this.atrSelectionReqdInd = value;
    }

    /**
     * Gets the value of the memberCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCaseNumber() {
        return memberCaseNumber;
    }

    /**
     * Sets the value of the memberCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCaseNumber(String value) {
        this.memberCaseNumber = value;
    }

    /**
     * Gets the value of the disputeCategoryCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCategoryCondition() {
        return disputeCategoryCondition;
    }

    /**
     * Sets the value of the disputeCategoryCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCategoryCondition(String value) {
        this.disputeCategoryCondition = value;
    }

    /**
     * Gets the value of the createDisputeFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getCreateDisputeFinancial() {
        return createDisputeFinancial;
    }

    /**
     * Sets the value of the createDisputeFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setCreateDisputeFinancial(YNType value) {
        this.createDisputeFinancial = value;
    }

    /**
     * Gets the value of the transactionMessageFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionMessageFormat() {
        return transactionMessageFormat;
    }

    /**
     * Sets the value of the transactionMessageFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionMessageFormat(String value) {
        this.transactionMessageFormat = value;
    }

    /**
     * Gets the value of the questionnaireRecalledDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getQuestionnaireRecalledDate() {
        return questionnaireRecalledDate;
    }

    /**
     * Sets the value of the questionnaireRecalledDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setQuestionnaireRecalledDate(XMLGregorianCalendar value) {
        this.questionnaireRecalledDate = value;
    }

    /**
     * Gets the value of the domProcQualifiedCaseInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDomProcQualifiedCaseInd() {
        return domProcQualifiedCaseInd;
    }

    /**
     * Sets the value of the domProcQualifiedCaseInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDomProcQualifiedCaseInd(Boolean value) {
        this.domProcQualifiedCaseInd = value;
    }

    /**
     * Gets the value of the disputeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeCategoryType }
     *     
     */
    public DisputeCategoryType getDisputeCategory() {
        return disputeCategory;
    }

    /**
     * Sets the value of the disputeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeCategoryType }
     *     
     */
    public void setDisputeCategory(DisputeCategoryType value) {
        this.disputeCategory = value;
    }

    /**
     * Gets the value of the disputeCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCondition() {
        return disputeCondition;
    }

    /**
     * Sets the value of the disputeCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCondition(String value) {
        this.disputeCondition = value;
    }

    /**
     * Gets the value of the disputeCardholderInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeCardholderInfoType }
     *     
     */
    public DisputeCardholderInfoType getDisputeCardholderInfo() {
        return disputeCardholderInfo;
    }

    /**
     * Sets the value of the disputeCardholderInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeCardholderInfoType }
     *     
     */
    public void setDisputeCardholderInfo(DisputeCardholderInfoType value) {
        this.disputeCardholderInfo = value;
    }

    /**
     * Gets the value of the merchantContactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantContactInfoType }
     *     
     */
    public MerchantContactInfoType getMerchantContactInfo() {
        return merchantContactInfo;
    }

    /**
     * Sets the value of the merchantContactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantContactInfoType }
     *     
     */
    public void setMerchantContactInfo(MerchantContactInfoType value) {
        this.merchantContactInfo = value;
    }

    /**
     * Gets the value of the disputeHistorySummary property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeHistorySummaryType }
     *     
     */
    public DisputeHistorySummaryType getDisputeHistorySummary() {
        return disputeHistorySummary;
    }

    /**
     * Sets the value of the disputeHistorySummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeHistorySummaryType }
     *     
     */
    public void setDisputeHistorySummary(DisputeHistorySummaryType value) {
        this.disputeHistorySummary = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNote(String value) {
        this.note = value;
    }

    /**
     * Gets the value of the caseHistorySummary property.
     * 
     * @return
     *     possible object is
     *     {@link CaseHistorySummaryType }
     *     
     */
    public CaseHistorySummaryType getCaseHistorySummary() {
        return caseHistorySummary;
    }

    /**
     * Sets the value of the caseHistorySummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseHistorySummaryType }
     *     
     */
    public void setCaseHistorySummary(CaseHistorySummaryType value) {
        this.caseHistorySummary = value;
    }

    /**
     * Gets the value of the preArbResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeResponseType }
     *     
     */
    public DisputeResponseType getPreArbResponse() {
        return preArbResponse;
    }

    /**
     * Sets the value of the preArbResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeResponseType }
     *     
     */
    public void setPreArbResponse(DisputeResponseType value) {
        this.preArbResponse = value;
    }

    /**
     * Gets the value of the acceptanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAcceptanceAmount() {
        return acceptanceAmount;
    }

    /**
     * Sets the value of the acceptanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAcceptanceAmount(AmountType value) {
        this.acceptanceAmount = value;
    }

    /**
     * Gets the value of the providingNewInfoInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getProvidingNewInfoInd() {
        return providingNewInfoInd;
    }

    /**
     * Sets the value of the providingNewInfoInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setProvidingNewInfoInd(YNType value) {
        this.providingNewInfoInd = value;
    }

    /**
     * Gets the value of the newInformationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewInformationDetails() {
        return newInformationDetails;
    }

    /**
     * Sets the value of the newInformationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewInformationDetails(String value) {
        this.newInformationDetails = value;
    }

    /**
     * Gets the value of the liabilityNotAcceptedFully property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiabilityNotAcceptedFully() {
        return liabilityNotAcceptedFully;
    }

    /**
     * Sets the value of the liabilityNotAcceptedFully property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiabilityNotAcceptedFully(String value) {
        this.liabilityNotAcceptedFully = value;
    }

    /**
     * Gets the value of the issuerCertifiesCardholderCompEvidence property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getIssuerCertifiesCardholderCompEvidence() {
        return issuerCertifiesCardholderCompEvidence;
    }

    /**
     * Sets the value of the issuerCertifiesCardholderCompEvidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setIssuerCertifiesCardholderCompEvidence(YNType value) {
        this.issuerCertifiesCardholderCompEvidence = value;
    }

    /**
     * Gets the value of the cardholderNameAddressNotMatchInd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getCardholderNameAddressNotMatchInd() {
        return cardholderNameAddressNotMatchInd;
    }

    /**
     * Sets the value of the cardholderNameAddressNotMatchInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setCardholderNameAddressNotMatchInd(YNType value) {
        this.cardholderNameAddressNotMatchInd = value;
    }

    /**
     * Gets the value of the cardholderContinuesDispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderContinuesDispute() {
        return cardholderContinuesDispute;
    }

    /**
     * Sets the value of the cardholderContinuesDispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderContinuesDispute(String value) {
        this.cardholderContinuesDispute = value;
    }

    /**
     * Gets the value of the explainContinuingDispute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplainContinuingDispute() {
        return explainContinuingDispute;
    }

    /**
     * Sets the value of the explainContinuingDispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplainContinuingDispute(String value) {
        this.explainContinuingDispute = value;
    }

    /**
     * Gets the value of the cardholderRequiresATMRecordInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCardholderRequiresATMRecordInd() {
        return cardholderRequiresATMRecordInd;
    }

    /**
     * Sets the value of the cardholderRequiresATMRecordInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCardholderRequiresATMRecordInd(Boolean value) {
        this.cardholderRequiresATMRecordInd = value;
    }

    /**
     * Gets the value of the atmRecordRequiredForLegalInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isATMRecordRequiredForLegalInd() {
        return atmRecordRequiredForLegalInd;
    }

    /**
     * Sets the value of the atmRecordRequiredForLegalInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setATMRecordRequiredForLegalInd(Boolean value) {
        this.atmRecordRequiredForLegalInd = value;
    }

    /**
     * Gets the value of the explainATMRecordRequiredForLegal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExplainATMRecordRequiredForLegal() {
        return explainATMRecordRequiredForLegal;
    }

    /**
     * Sets the value of the explainATMRecordRequiredForLegal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExplainATMRecordRequiredForLegal(String value) {
        this.explainATMRecordRequiredForLegal = value;
    }

    /**
     * Gets the value of the issuerAcquirerContactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IssuerAcquirerContactInfoType }
     *     
     */
    public IssuerAcquirerContactInfoType getIssuerAcquirerContactInfo() {
        return issuerAcquirerContactInfo;
    }

    /**
     * Sets the value of the issuerAcquirerContactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuerAcquirerContactInfoType }
     *     
     */
    public void setIssuerAcquirerContactInfo(IssuerAcquirerContactInfoType value) {
        this.issuerAcquirerContactInfo = value;
    }

    /**
     * Gets the value of the recallInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecallInd() {
        return recallInd;
    }

    /**
     * Sets the value of the recallInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecallInd(Boolean value) {
        this.recallInd = value;
    }

    /**
     * Gets the value of the recallReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecallReason() {
        return recallReason;
    }

    /**
     * Sets the value of the recallReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecallReason(String value) {
        this.recallReason = value;
    }

    /**
     * Gets the value of the disputeImageAttachment property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeAttachmentDescriptorType }
     *     
     */
    public DisputeAttachmentDescriptorType getDisputeImageAttachment() {
        return disputeImageAttachment;
    }

    /**
     * Sets the value of the disputeImageAttachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeAttachmentDescriptorType }
     *     
     */
    public void setDisputeImageAttachment(DisputeAttachmentDescriptorType value) {
        this.disputeImageAttachment = value;
    }

    /**
     * Gets the value of the disputeAsImageResponseDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeAsImageResponseDescriptorType }
     *     
     */
    public DisputeAsImageResponseDescriptorType getDisputeAsImageResponseDescriptor() {
        return disputeAsImageResponseDescriptor;
    }

    /**
     * Sets the value of the disputeAsImageResponseDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeAsImageResponseDescriptorType }
     *     
     */
    public void setDisputeAsImageResponseDescriptor(DisputeAsImageResponseDescriptorType value) {
        this.disputeAsImageResponseDescriptor = value;
    }

}
