//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PreArbRespDisputeOnlyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreArbRespDisputeOnlyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}PreArbBaseGroup"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}PreFilingRespGroup"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreArbRespDisputeOnlyType", propOrder = {
    "disputeRuleSetCode",
    "disputeReasonCode",
    "disputeGroupCode",
    "disputeAmt",
    "exceptionCPD",
    "additionalInfoComments",
    "contactAddress",
    "contactBestTimeToCall",
    "contactCity",
    "contactCountryCode",
    "contactEmail",
    "contactFax",
    "contactName",
    "contactOptInInd",
    "contactPhone",
    "contactPostalCode",
    "contactStateCode",
    "daysToRespond",
    "lastDayToRespond",
    "initiatePreFilingReason",
    "initiatorEmail",
    "initiatorFax",
    "initiatorName",
    "initiatorPhone",
    "memberCaseNumber",
    "merchantURL",
    "recallInd",
    "recallReason",
    "firstChargebackCPD",
    "firstChargebackDisputeAmount",
    "firstChargebackDisputeReasonCode",
    "newInformationInd",
    "compellingEvidenceCardholderContactInd",
    "certificationCardholderReviewedCompellingEvidenceInd",
    "certificationCardholderNameAddrDoesNotMatchIssuerRecordInd",
    "continuationOfDisputeExplanation",
    "issuerCertifiedCardholderATMTransRecordInd",
    "issuerCertifiedLegalOrInsurancePurposeInd",
    "issuerCertifiedLegalOrInsurancePurposeExplanation",
    "representmentCPD",
    "representmentDisputeAmount",
    "representmentDisputeReasonCode",
    "retrievalRequestDate",
    "retrievalRequestReasonCode",
    "secondFirstChargebackCPD",
    "secondFirstChargebackDisputeAmount",
    "secondFirstChargebackDisputeReasonCode",
    "secondRepresentmentCPD",
    "secondRepresentmentDisputeAmount",
    "secondRepresentmentDisputeReasonCode",
    "secondChargebackCPD",
    "secondChargebackDisputeAmount",
    "secondChargebackDisputeReasonCode",
    "preArbitrationCPD",
    "preArbitrationDisputeAmount",
    "preArbitrationReasonCode",
    "rfcCpdFromTranCpd",
    "rfcResponseCpdFromRfcCpd",
    "cbCpdFromTranCpd",
    "cbCpdFromRfcCpd",
    "cbCpdFromRfcResponseCpd",
    "repreCpdFromCBCpd",
    "preArbDateFromRepreCpd",
    "secondCBCpdFromRepreCpd",
    "preArbDateFromSecondCBCpd",
    "caseFilingDateFromSecondCBCpd",
    "acceptanceAmount",
    "continuePreFilingReason",
    "partialAcceptanceReason",
    "responseCode",
    "whenAmountSentDate",
    "transferFundsNowCd"
})
public class PreArbRespDisputeOnlyType {

    @XmlElement(name = "DisputeRuleSetCode")
    @XmlSchemaType(name = "string")
    protected RuleSetCodeType disputeRuleSetCode;
    @XmlElement(name = "DisputeReasonCode")
    protected String disputeReasonCode;
    @XmlElement(name = "DisputeGroupCode")
    protected String disputeGroupCode;
    @XmlElement(name = "DisputeAmt")
    protected org.incomm.generated.RepreType.DisputeAmt disputeAmt;
    @XmlElement(name = "ExceptionCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exceptionCPD;
    @XmlElement(name = "AdditionalInfoComments")
    protected String additionalInfoComments;
    @XmlElement(name = "ContactAddress")
    protected String contactAddress;
    @XmlElement(name = "ContactBestTimeToCall")
    protected String contactBestTimeToCall;
    @XmlElement(name = "ContactCity")
    protected String contactCity;
    @XmlElement(name = "ContactCountryCode")
    protected String contactCountryCode;
    @XmlElement(name = "ContactEmail")
    protected String contactEmail;
    @XmlElement(name = "ContactFax")
    protected String contactFax;
    @XmlElement(name = "ContactName")
    protected String contactName;
    @XmlElement(name = "ContactOptInInd")
    protected Boolean contactOptInInd;
    @XmlElement(name = "ContactPhone")
    protected String contactPhone;
    @XmlElement(name = "ContactPostalCode")
    protected String contactPostalCode;
    @XmlElement(name = "ContactStateCode")
    protected String contactStateCode;
    @XmlElement(name = "DaysToRespond")
    protected Integer daysToRespond;
    @XmlElement(name = "LastDayToRespond")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastDayToRespond;
    @XmlElement(name = "InitiatePreFilingReason")
    protected String initiatePreFilingReason;
    @XmlElement(name = "InitiatorEmail")
    protected String initiatorEmail;
    @XmlElement(name = "InitiatorFax")
    protected String initiatorFax;
    @XmlElement(name = "InitiatorName")
    protected String initiatorName;
    @XmlElement(name = "InitiatorPhone")
    protected String initiatorPhone;
    @XmlElement(name = "MemberCaseNumber")
    protected String memberCaseNumber;
    @XmlElement(name = "MerchantURL")
    protected String merchantURL;
    @XmlElement(name = "RecallInd")
    protected Boolean recallInd;
    @XmlElement(name = "RecallReason")
    protected String recallReason;
    @XmlElement(name = "FirstChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstChargebackCPD;
    @XmlElement(name = "FirstChargebackDisputeAmount")
    protected AmountType firstChargebackDisputeAmount;
    @XmlElement(name = "FirstChargebackDisputeReasonCode")
    protected String firstChargebackDisputeReasonCode;
    @XmlElement(name = "NewInformationInd")
    protected Boolean newInformationInd;
    @XmlElement(name = "CompellingEvidenceCardholderContactInd")
    protected Boolean compellingEvidenceCardholderContactInd;
    @XmlElement(name = "CertificationCardholderReviewedCompellingEvidenceInd")
    protected Boolean certificationCardholderReviewedCompellingEvidenceInd;
    @XmlElement(name = "CertificationCardholderNameAddrDoesNotMatchIssuerRecordInd")
    protected Boolean certificationCardholderNameAddrDoesNotMatchIssuerRecordInd;
    @XmlElement(name = "ContinuationOfDisputeExplanation")
    protected String continuationOfDisputeExplanation;
    @XmlElement(name = "IssuerCertifiedCardholderATMTransRecordInd")
    protected Boolean issuerCertifiedCardholderATMTransRecordInd;
    @XmlElement(name = "IssuerCertifiedLegalOrInsurancePurposeInd")
    protected Boolean issuerCertifiedLegalOrInsurancePurposeInd;
    @XmlElement(name = "IssuerCertifiedLegalOrInsurancePurposeExplanation")
    protected String issuerCertifiedLegalOrInsurancePurposeExplanation;
    @XmlElement(name = "RepresentmentCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar representmentCPD;
    @XmlElement(name = "RepresentmentDisputeAmount")
    protected AmountType representmentDisputeAmount;
    @XmlElement(name = "RepresentmentDisputeReasonCode")
    protected String representmentDisputeReasonCode;
    @XmlElement(name = "RetrievalRequestDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar retrievalRequestDate;
    @XmlElement(name = "RetrievalRequestReasonCode")
    protected String retrievalRequestReasonCode;
    @XmlElement(name = "SecondFirstChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondFirstChargebackCPD;
    @XmlElement(name = "SecondFirstChargebackDisputeAmount")
    protected AmountType secondFirstChargebackDisputeAmount;
    @XmlElement(name = "SecondFirstChargebackDisputeReasonCode")
    protected String secondFirstChargebackDisputeReasonCode;
    @XmlElement(name = "SecondRepresentmentCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondRepresentmentCPD;
    @XmlElement(name = "SecondRepresentmentDisputeAmount")
    protected AmountType secondRepresentmentDisputeAmount;
    @XmlElement(name = "SecondRepresentmentDisputeReasonCode")
    protected String secondRepresentmentDisputeReasonCode;
    @XmlElement(name = "SecondChargebackCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar secondChargebackCPD;
    @XmlElement(name = "SecondChargebackDisputeAmount")
    protected AmountType secondChargebackDisputeAmount;
    @XmlElement(name = "SecondChargebackDisputeReasonCode")
    protected String secondChargebackDisputeReasonCode;
    @XmlElement(name = "PreArbitrationCPD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar preArbitrationCPD;
    @XmlElement(name = "PreArbitrationDisputeAmount")
    protected AmountType preArbitrationDisputeAmount;
    @XmlElement(name = "PreArbitrationReasonCode")
    protected String preArbitrationReasonCode;
    @XmlElement(name = "RfcCpdFromTranCpd")
    protected String rfcCpdFromTranCpd;
    @XmlElement(name = "RfcResponseCpdFromRfcCpd")
    protected String rfcResponseCpdFromRfcCpd;
    @XmlElement(name = "CBCpdFromTranCpd")
    protected String cbCpdFromTranCpd;
    @XmlElement(name = "CBCpdFromRfcCpd")
    protected String cbCpdFromRfcCpd;
    @XmlElement(name = "CBCpdFromRfcResponseCpd")
    protected String cbCpdFromRfcResponseCpd;
    @XmlElement(name = "RepreCpdFromCBCpd")
    protected String repreCpdFromCBCpd;
    @XmlElement(name = "PreArbDateFromRepreCpd")
    protected String preArbDateFromRepreCpd;
    @XmlElement(name = "SecondCBCpdFromRepreCpd")
    protected String secondCBCpdFromRepreCpd;
    @XmlElement(name = "PreArbDateFromSecondCBCpd")
    protected String preArbDateFromSecondCBCpd;
    @XmlElement(name = "CaseFilingDateFromSecondCBCpd")
    protected String caseFilingDateFromSecondCBCpd;
    @XmlElement(name = "AcceptanceAmount")
    protected AmountType acceptanceAmount;
    @XmlElement(name = "ContinuePreFilingReason")
    protected String continuePreFilingReason;
    @XmlElement(name = "PartialAcceptanceReason")
    protected String partialAcceptanceReason;
    @XmlElement(name = "ResponseCode")
    protected String responseCode;
    @XmlElement(name = "WhenAmountSentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar whenAmountSentDate;
    @XmlElement(name = "TransferFundsNowCd")
    @XmlSchemaType(name = "string")
    protected YNType transferFundsNowCd;

    /**
     * Note: No longer used by VROL
     * 
     * @return
     *     possible object is
     *     {@link RuleSetCodeType }
     *     
     */
    public RuleSetCodeType getDisputeRuleSetCode() {
        return disputeRuleSetCode;
    }

    /**
     * Sets the value of the disputeRuleSetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleSetCodeType }
     *     
     */
    public void setDisputeRuleSetCode(RuleSetCodeType value) {
        this.disputeRuleSetCode = value;
    }

    /**
     * Gets the value of the disputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeReasonCode() {
        return disputeReasonCode;
    }

    /**
     * Sets the value of the disputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeReasonCode(String value) {
        this.disputeReasonCode = value;
    }

    /**
     * Gets the value of the disputeGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeGroupCode() {
        return disputeGroupCode;
    }

    /**
     * Sets the value of the disputeGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeGroupCode(String value) {
        this.disputeGroupCode = value;
    }

    /**
     * Gets the value of the disputeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link org.incomm.generated.RepreType.DisputeAmt }
     *     
     */
    public org.incomm.generated.RepreType.DisputeAmt getDisputeAmt() {
        return disputeAmt;
    }

    /**
     * Sets the value of the disputeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.incomm.generated.RepreType.DisputeAmt }
     *     
     */
    public void setDisputeAmt(org.incomm.generated.RepreType.DisputeAmt value) {
        this.disputeAmt = value;
    }

    /**
     * Gets the value of the exceptionCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExceptionCPD() {
        return exceptionCPD;
    }

    /**
     * Sets the value of the exceptionCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExceptionCPD(XMLGregorianCalendar value) {
        this.exceptionCPD = value;
    }

    /**
     * Gets the value of the additionalInfoComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfoComments() {
        return additionalInfoComments;
    }

    /**
     * Sets the value of the additionalInfoComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfoComments(String value) {
        this.additionalInfoComments = value;
    }

    /**
     * Gets the value of the contactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * Sets the value of the contactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress(String value) {
        this.contactAddress = value;
    }

    /**
     * Gets the value of the contactBestTimeToCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactBestTimeToCall() {
        return contactBestTimeToCall;
    }

    /**
     * Sets the value of the contactBestTimeToCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactBestTimeToCall(String value) {
        this.contactBestTimeToCall = value;
    }

    /**
     * Gets the value of the contactCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCity() {
        return contactCity;
    }

    /**
     * Sets the value of the contactCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCity(String value) {
        this.contactCity = value;
    }

    /**
     * Gets the value of the contactCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCountryCode() {
        return contactCountryCode;
    }

    /**
     * Sets the value of the contactCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCountryCode(String value) {
        this.contactCountryCode = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * Sets the value of the contactFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFax(String value) {
        this.contactFax = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the contactOptInInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactOptInInd() {
        return contactOptInInd;
    }

    /**
     * Sets the value of the contactOptInInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactOptInInd(Boolean value) {
        this.contactOptInInd = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPostalCode() {
        return contactPostalCode;
    }

    /**
     * Sets the value of the contactPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPostalCode(String value) {
        this.contactPostalCode = value;
    }

    /**
     * Gets the value of the contactStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactStateCode() {
        return contactStateCode;
    }

    /**
     * Sets the value of the contactStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactStateCode(String value) {
        this.contactStateCode = value;
    }

    /**
     * Gets the value of the daysToRespond property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysToRespond() {
        return daysToRespond;
    }

    /**
     * Sets the value of the daysToRespond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysToRespond(Integer value) {
        this.daysToRespond = value;
    }

    /**
     * Gets the value of the lastDayToRespond property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDayToRespond() {
        return lastDayToRespond;
    }

    /**
     * Sets the value of the lastDayToRespond property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDayToRespond(XMLGregorianCalendar value) {
        this.lastDayToRespond = value;
    }

    /**
     * Gets the value of the initiatePreFilingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatePreFilingReason() {
        return initiatePreFilingReason;
    }

    /**
     * Sets the value of the initiatePreFilingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatePreFilingReason(String value) {
        this.initiatePreFilingReason = value;
    }

    /**
     * Gets the value of the initiatorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorEmail() {
        return initiatorEmail;
    }

    /**
     * Sets the value of the initiatorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorEmail(String value) {
        this.initiatorEmail = value;
    }

    /**
     * Gets the value of the initiatorFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorFax() {
        return initiatorFax;
    }

    /**
     * Sets the value of the initiatorFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorFax(String value) {
        this.initiatorFax = value;
    }

    /**
     * Gets the value of the initiatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorName() {
        return initiatorName;
    }

    /**
     * Sets the value of the initiatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorName(String value) {
        this.initiatorName = value;
    }

    /**
     * Gets the value of the initiatorPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorPhone() {
        return initiatorPhone;
    }

    /**
     * Sets the value of the initiatorPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorPhone(String value) {
        this.initiatorPhone = value;
    }

    /**
     * Gets the value of the memberCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCaseNumber() {
        return memberCaseNumber;
    }

    /**
     * Sets the value of the memberCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCaseNumber(String value) {
        this.memberCaseNumber = value;
    }

    /**
     * Gets the value of the merchantURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantURL() {
        return merchantURL;
    }

    /**
     * Sets the value of the merchantURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantURL(String value) {
        this.merchantURL = value;
    }

    /**
     * Gets the value of the recallInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecallInd() {
        return recallInd;
    }

    /**
     * Sets the value of the recallInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecallInd(Boolean value) {
        this.recallInd = value;
    }

    /**
     * Gets the value of the recallReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecallReason() {
        return recallReason;
    }

    /**
     * Sets the value of the recallReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecallReason(String value) {
        this.recallReason = value;
    }

    /**
     * Gets the value of the firstChargebackCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstChargebackCPD() {
        return firstChargebackCPD;
    }

    /**
     * Sets the value of the firstChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstChargebackCPD(XMLGregorianCalendar value) {
        this.firstChargebackCPD = value;
    }

    /**
     * Gets the value of the firstChargebackDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFirstChargebackDisputeAmount() {
        return firstChargebackDisputeAmount;
    }

    /**
     * Sets the value of the firstChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFirstChargebackDisputeAmount(AmountType value) {
        this.firstChargebackDisputeAmount = value;
    }

    /**
     * Gets the value of the firstChargebackDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstChargebackDisputeReasonCode() {
        return firstChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the firstChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstChargebackDisputeReasonCode(String value) {
        this.firstChargebackDisputeReasonCode = value;
    }

    /**
     * Gets the value of the newInformationInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNewInformationInd() {
        return newInformationInd;
    }

    /**
     * Sets the value of the newInformationInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewInformationInd(Boolean value) {
        this.newInformationInd = value;
    }

    /**
     * Gets the value of the compellingEvidenceCardholderContactInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCompellingEvidenceCardholderContactInd() {
        return compellingEvidenceCardholderContactInd;
    }

    /**
     * Sets the value of the compellingEvidenceCardholderContactInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompellingEvidenceCardholderContactInd(Boolean value) {
        this.compellingEvidenceCardholderContactInd = value;
    }

    /**
     * Gets the value of the certificationCardholderReviewedCompellingEvidenceInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCertificationCardholderReviewedCompellingEvidenceInd() {
        return certificationCardholderReviewedCompellingEvidenceInd;
    }

    /**
     * Sets the value of the certificationCardholderReviewedCompellingEvidenceInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCertificationCardholderReviewedCompellingEvidenceInd(Boolean value) {
        this.certificationCardholderReviewedCompellingEvidenceInd = value;
    }

    /**
     * Gets the value of the certificationCardholderNameAddrDoesNotMatchIssuerRecordInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCertificationCardholderNameAddrDoesNotMatchIssuerRecordInd() {
        return certificationCardholderNameAddrDoesNotMatchIssuerRecordInd;
    }

    /**
     * Sets the value of the certificationCardholderNameAddrDoesNotMatchIssuerRecordInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCertificationCardholderNameAddrDoesNotMatchIssuerRecordInd(Boolean value) {
        this.certificationCardholderNameAddrDoesNotMatchIssuerRecordInd = value;
    }

    /**
     * Gets the value of the continuationOfDisputeExplanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinuationOfDisputeExplanation() {
        return continuationOfDisputeExplanation;
    }

    /**
     * Sets the value of the continuationOfDisputeExplanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinuationOfDisputeExplanation(String value) {
        this.continuationOfDisputeExplanation = value;
    }

    /**
     * Gets the value of the issuerCertifiedCardholderATMTransRecordInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIssuerCertifiedCardholderATMTransRecordInd() {
        return issuerCertifiedCardholderATMTransRecordInd;
    }

    /**
     * Sets the value of the issuerCertifiedCardholderATMTransRecordInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIssuerCertifiedCardholderATMTransRecordInd(Boolean value) {
        this.issuerCertifiedCardholderATMTransRecordInd = value;
    }

    /**
     * Gets the value of the issuerCertifiedLegalOrInsurancePurposeInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIssuerCertifiedLegalOrInsurancePurposeInd() {
        return issuerCertifiedLegalOrInsurancePurposeInd;
    }

    /**
     * Sets the value of the issuerCertifiedLegalOrInsurancePurposeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIssuerCertifiedLegalOrInsurancePurposeInd(Boolean value) {
        this.issuerCertifiedLegalOrInsurancePurposeInd = value;
    }

    /**
     * Gets the value of the issuerCertifiedLegalOrInsurancePurposeExplanation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCertifiedLegalOrInsurancePurposeExplanation() {
        return issuerCertifiedLegalOrInsurancePurposeExplanation;
    }

    /**
     * Sets the value of the issuerCertifiedLegalOrInsurancePurposeExplanation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCertifiedLegalOrInsurancePurposeExplanation(String value) {
        this.issuerCertifiedLegalOrInsurancePurposeExplanation = value;
    }

    /**
     * Gets the value of the representmentCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRepresentmentCPD() {
        return representmentCPD;
    }

    /**
     * Sets the value of the representmentCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRepresentmentCPD(XMLGregorianCalendar value) {
        this.representmentCPD = value;
    }

    /**
     * Gets the value of the representmentDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getRepresentmentDisputeAmount() {
        return representmentDisputeAmount;
    }

    /**
     * Sets the value of the representmentDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setRepresentmentDisputeAmount(AmountType value) {
        this.representmentDisputeAmount = value;
    }

    /**
     * Gets the value of the representmentDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepresentmentDisputeReasonCode() {
        return representmentDisputeReasonCode;
    }

    /**
     * Sets the value of the representmentDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepresentmentDisputeReasonCode(String value) {
        this.representmentDisputeReasonCode = value;
    }

    /**
     * Gets the value of the retrievalRequestDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRetrievalRequestDate() {
        return retrievalRequestDate;
    }

    /**
     * Sets the value of the retrievalRequestDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRetrievalRequestDate(XMLGregorianCalendar value) {
        this.retrievalRequestDate = value;
    }

    /**
     * Gets the value of the retrievalRequestReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetrievalRequestReasonCode() {
        return retrievalRequestReasonCode;
    }

    /**
     * Sets the value of the retrievalRequestReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetrievalRequestReasonCode(String value) {
        this.retrievalRequestReasonCode = value;
    }

    /**
     * Gets the value of the secondFirstChargebackCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondFirstChargebackCPD() {
        return secondFirstChargebackCPD;
    }

    /**
     * Sets the value of the secondFirstChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondFirstChargebackCPD(XMLGregorianCalendar value) {
        this.secondFirstChargebackCPD = value;
    }

    /**
     * Gets the value of the secondFirstChargebackDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondFirstChargebackDisputeAmount() {
        return secondFirstChargebackDisputeAmount;
    }

    /**
     * Sets the value of the secondFirstChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondFirstChargebackDisputeAmount(AmountType value) {
        this.secondFirstChargebackDisputeAmount = value;
    }

    /**
     * Gets the value of the secondFirstChargebackDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondFirstChargebackDisputeReasonCode() {
        return secondFirstChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the secondFirstChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondFirstChargebackDisputeReasonCode(String value) {
        this.secondFirstChargebackDisputeReasonCode = value;
    }

    /**
     * Gets the value of the secondRepresentmentCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondRepresentmentCPD() {
        return secondRepresentmentCPD;
    }

    /**
     * Sets the value of the secondRepresentmentCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondRepresentmentCPD(XMLGregorianCalendar value) {
        this.secondRepresentmentCPD = value;
    }

    /**
     * Gets the value of the secondRepresentmentDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondRepresentmentDisputeAmount() {
        return secondRepresentmentDisputeAmount;
    }

    /**
     * Sets the value of the secondRepresentmentDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondRepresentmentDisputeAmount(AmountType value) {
        this.secondRepresentmentDisputeAmount = value;
    }

    /**
     * Gets the value of the secondRepresentmentDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondRepresentmentDisputeReasonCode() {
        return secondRepresentmentDisputeReasonCode;
    }

    /**
     * Sets the value of the secondRepresentmentDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondRepresentmentDisputeReasonCode(String value) {
        this.secondRepresentmentDisputeReasonCode = value;
    }

    /**
     * Gets the value of the secondChargebackCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSecondChargebackCPD() {
        return secondChargebackCPD;
    }

    /**
     * Sets the value of the secondChargebackCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSecondChargebackCPD(XMLGregorianCalendar value) {
        this.secondChargebackCPD = value;
    }

    /**
     * Gets the value of the secondChargebackDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getSecondChargebackDisputeAmount() {
        return secondChargebackDisputeAmount;
    }

    /**
     * Sets the value of the secondChargebackDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setSecondChargebackDisputeAmount(AmountType value) {
        this.secondChargebackDisputeAmount = value;
    }

    /**
     * Gets the value of the secondChargebackDisputeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondChargebackDisputeReasonCode() {
        return secondChargebackDisputeReasonCode;
    }

    /**
     * Sets the value of the secondChargebackDisputeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondChargebackDisputeReasonCode(String value) {
        this.secondChargebackDisputeReasonCode = value;
    }

    /**
     * Gets the value of the preArbitrationCPD property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPreArbitrationCPD() {
        return preArbitrationCPD;
    }

    /**
     * Sets the value of the preArbitrationCPD property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPreArbitrationCPD(XMLGregorianCalendar value) {
        this.preArbitrationCPD = value;
    }

    /**
     * Gets the value of the preArbitrationDisputeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getPreArbitrationDisputeAmount() {
        return preArbitrationDisputeAmount;
    }

    /**
     * Sets the value of the preArbitrationDisputeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setPreArbitrationDisputeAmount(AmountType value) {
        this.preArbitrationDisputeAmount = value;
    }

    /**
     * Gets the value of the preArbitrationReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbitrationReasonCode() {
        return preArbitrationReasonCode;
    }

    /**
     * Sets the value of the preArbitrationReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbitrationReasonCode(String value) {
        this.preArbitrationReasonCode = value;
    }

    /**
     * Gets the value of the rfcCpdFromTranCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcCpdFromTranCpd() {
        return rfcCpdFromTranCpd;
    }

    /**
     * Sets the value of the rfcCpdFromTranCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcCpdFromTranCpd(String value) {
        this.rfcCpdFromTranCpd = value;
    }

    /**
     * Gets the value of the rfcResponseCpdFromRfcCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRfcResponseCpdFromRfcCpd() {
        return rfcResponseCpdFromRfcCpd;
    }

    /**
     * Sets the value of the rfcResponseCpdFromRfcCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRfcResponseCpdFromRfcCpd(String value) {
        this.rfcResponseCpdFromRfcCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromTranCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromTranCpd() {
        return cbCpdFromTranCpd;
    }

    /**
     * Sets the value of the cbCpdFromTranCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromTranCpd(String value) {
        this.cbCpdFromTranCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromRfcCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromRfcCpd() {
        return cbCpdFromRfcCpd;
    }

    /**
     * Sets the value of the cbCpdFromRfcCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromRfcCpd(String value) {
        this.cbCpdFromRfcCpd = value;
    }

    /**
     * Gets the value of the cbCpdFromRfcResponseCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCBCpdFromRfcResponseCpd() {
        return cbCpdFromRfcResponseCpd;
    }

    /**
     * Sets the value of the cbCpdFromRfcResponseCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCBCpdFromRfcResponseCpd(String value) {
        this.cbCpdFromRfcResponseCpd = value;
    }

    /**
     * Gets the value of the repreCpdFromCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepreCpdFromCBCpd() {
        return repreCpdFromCBCpd;
    }

    /**
     * Sets the value of the repreCpdFromCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepreCpdFromCBCpd(String value) {
        this.repreCpdFromCBCpd = value;
    }

    /**
     * Gets the value of the preArbDateFromRepreCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbDateFromRepreCpd() {
        return preArbDateFromRepreCpd;
    }

    /**
     * Sets the value of the preArbDateFromRepreCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbDateFromRepreCpd(String value) {
        this.preArbDateFromRepreCpd = value;
    }

    /**
     * Gets the value of the secondCBCpdFromRepreCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondCBCpdFromRepreCpd() {
        return secondCBCpdFromRepreCpd;
    }

    /**
     * Sets the value of the secondCBCpdFromRepreCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondCBCpdFromRepreCpd(String value) {
        this.secondCBCpdFromRepreCpd = value;
    }

    /**
     * Gets the value of the preArbDateFromSecondCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreArbDateFromSecondCBCpd() {
        return preArbDateFromSecondCBCpd;
    }

    /**
     * Sets the value of the preArbDateFromSecondCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreArbDateFromSecondCBCpd(String value) {
        this.preArbDateFromSecondCBCpd = value;
    }

    /**
     * Gets the value of the caseFilingDateFromSecondCBCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaseFilingDateFromSecondCBCpd() {
        return caseFilingDateFromSecondCBCpd;
    }

    /**
     * Sets the value of the caseFilingDateFromSecondCBCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaseFilingDateFromSecondCBCpd(String value) {
        this.caseFilingDateFromSecondCBCpd = value;
    }

    /**
     * Gets the value of the acceptanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAcceptanceAmount() {
        return acceptanceAmount;
    }

    /**
     * Sets the value of the acceptanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAcceptanceAmount(AmountType value) {
        this.acceptanceAmount = value;
    }

    /**
     * Gets the value of the continuePreFilingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinuePreFilingReason() {
        return continuePreFilingReason;
    }

    /**
     * Sets the value of the continuePreFilingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinuePreFilingReason(String value) {
        this.continuePreFilingReason = value;
    }

    /**
     * Gets the value of the partialAcceptanceReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialAcceptanceReason() {
        return partialAcceptanceReason;
    }

    /**
     * Sets the value of the partialAcceptanceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialAcceptanceReason(String value) {
        this.partialAcceptanceReason = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the whenAmountSentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWhenAmountSentDate() {
        return whenAmountSentDate;
    }

    /**
     * Sets the value of the whenAmountSentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWhenAmountSentDate(XMLGregorianCalendar value) {
        this.whenAmountSentDate = value;
    }

    /**
     * Gets the value of the transferFundsNowCd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getTransferFundsNowCd() {
        return transferFundsNowCd;
    }

    /**
     * Sets the value of the transferFundsNowCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setTransferFundsNowCd(YNType value) {
        this.transferFundsNowCd = value;
    }

}
