//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for StopPaymentDescriptorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StopPaymentDescriptorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.visa.com/ROLSI}StopPaymentGroup"/&gt;
 *       &lt;attribute name="operation" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="add"/&gt;
 *             &lt;enumeration value="update"/&gt;
 *             &lt;enumeration value="delete"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StopPaymentDescriptorType", propOrder = {
    "cancellationType",
    "cancellationTypeDescription",
    "accountNumber",
    "cardAcceptorId",
    "merchantVerificationValue",
    "merchantName",
    "merchantCategoryCode",
    "expirationDate",
    "acquirerInstCountryCode",
    "transactionAmount",
    "amountRange"
})
public class StopPaymentDescriptorType {

    @XmlElement(name = "CancellationType", required = true)
    @XmlSchemaType(name = "string")
    protected PPCSCancellationType cancellationType;
    @XmlElement(name = "CancellationTypeDescription")
    protected String cancellationTypeDescription;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "CardAcceptorId")
    protected String cardAcceptorId;
    @XmlElement(name = "MerchantVerificationValue")
    protected String merchantVerificationValue;
    @XmlElement(name = "MerchantName")
    protected String merchantName;
    @XmlElement(name = "MerchantCategoryCode")
    protected String merchantCategoryCode;
    @XmlElement(name = "ExpirationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expirationDate;
    @XmlElement(name = "AcquirerInstCountryCode")
    protected String acquirerInstCountryCode;
    @XmlElement(name = "TransactionAmount")
    protected BigDecimal transactionAmount;
    @XmlElement(name = "AmountRange")
    protected org.incomm.generated.StopPaymentOrderDetailsType.AmountRange amountRange;
    @XmlAttribute(name = "operation", required = true)
    protected String operation;

    /**
     * Gets the value of the cancellationType property.
     * 
     * @return
     *     possible object is
     *     {@link PPCSCancellationType }
     *     
     */
    public PPCSCancellationType getCancellationType() {
        return cancellationType;
    }

    /**
     * Sets the value of the cancellationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PPCSCancellationType }
     *     
     */
    public void setCancellationType(PPCSCancellationType value) {
        this.cancellationType = value;
    }

    /**
     * Gets the value of the cancellationTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationTypeDescription() {
        return cancellationTypeDescription;
    }

    /**
     * Sets the value of the cancellationTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationTypeDescription(String value) {
        this.cancellationTypeDescription = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the cardAcceptorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardAcceptorId() {
        return cardAcceptorId;
    }

    /**
     * Sets the value of the cardAcceptorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardAcceptorId(String value) {
        this.cardAcceptorId = value;
    }

    /**
     * Gets the value of the merchantVerificationValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantVerificationValue() {
        return merchantVerificationValue;
    }

    /**
     * Sets the value of the merchantVerificationValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantVerificationValue(String value) {
        this.merchantVerificationValue = value;
    }

    /**
     * Gets the value of the merchantName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Sets the value of the merchantName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantName(String value) {
        this.merchantName = value;
    }

    /**
     * Gets the value of the merchantCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantCategoryCode() {
        return merchantCategoryCode;
    }

    /**
     * Sets the value of the merchantCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantCategoryCode(String value) {
        this.merchantCategoryCode = value;
    }

    /**
     * Gets the value of the expirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpirationDate() {
        return expirationDate;
    }

    /**
     * Sets the value of the expirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpirationDate(XMLGregorianCalendar value) {
        this.expirationDate = value;
    }

    /**
     * Gets the value of the acquirerInstCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerInstCountryCode() {
        return acquirerInstCountryCode;
    }

    /**
     * Sets the value of the acquirerInstCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerInstCountryCode(String value) {
        this.acquirerInstCountryCode = value;
    }

    /**
     * Gets the value of the transactionAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTransactionAmount() {
        return transactionAmount;
    }

    /**
     * Sets the value of the transactionAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTransactionAmount(BigDecimal value) {
        this.transactionAmount = value;
    }

    /**
     * Gets the value of the amountRange property.
     * 
     * @return
     *     possible object is
     *     {@link org.incomm.generated.StopPaymentOrderDetailsType.AmountRange }
     *     
     */
    public org.incomm.generated.StopPaymentOrderDetailsType.AmountRange getAmountRange() {
        return amountRange;
    }

    /**
     * Sets the value of the amountRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.incomm.generated.StopPaymentOrderDetailsType.AmountRange }
     *     
     */
    public void setAmountRange(org.incomm.generated.StopPaymentOrderDetailsType.AmountRange value) {
        this.amountRange = value;
    }

    /**
     * Gets the value of the operation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperation() {
        return operation;
    }

    /**
     * Sets the value of the operation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperation(String value) {
        this.operation = value;
    }

}
