//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ExtendedCreateCaseInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedCreateCaseInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}CreateCaseInfoType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CardholderContactDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}CardholderWrittenNotiffDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}FollowUpDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RegEIndicator" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RegZIndicator" minOccurs="0"/&gt;
 *         &lt;element name="ProvisionalCreditIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}MemberCaseNumber" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedCreateCaseInfoType", propOrder = {
    "cardholderContactDate",
    "cardholderWrittenNotiffDate",
    "followUpDate",
    "regEIndicator",
    "regZIndicator",
    "provisionalCreditIndicator",
    "memberCaseNumber"
})
@XmlSeeAlso({
    RTSIExtendedCreateCaseInfoType.class
})
public class ExtendedCreateCaseInfoType
    extends CreateCaseInfoType
{

    @XmlElement(name = "CardholderContactDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cardholderContactDate;
    @XmlElement(name = "CardholderWrittenNotiffDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar cardholderWrittenNotiffDate;
    @XmlElement(name = "FollowUpDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar followUpDate;
    @XmlElement(name = "RegEIndicator")
    protected Boolean regEIndicator;
    @XmlElement(name = "RegZIndicator")
    protected Boolean regZIndicator;
    @XmlElement(name = "ProvisionalCreditIndicator")
    protected Boolean provisionalCreditIndicator;
    @XmlElement(name = "MemberCaseNumber")
    protected String memberCaseNumber;

    /**
     * Gets the value of the cardholderContactDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardholderContactDate() {
        return cardholderContactDate;
    }

    /**
     * Sets the value of the cardholderContactDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardholderContactDate(XMLGregorianCalendar value) {
        this.cardholderContactDate = value;
    }

    /**
     * Gets the value of the cardholderWrittenNotiffDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCardholderWrittenNotiffDate() {
        return cardholderWrittenNotiffDate;
    }

    /**
     * Sets the value of the cardholderWrittenNotiffDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCardholderWrittenNotiffDate(XMLGregorianCalendar value) {
        this.cardholderWrittenNotiffDate = value;
    }

    /**
     * Gets the value of the followUpDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFollowUpDate() {
        return followUpDate;
    }

    /**
     * Sets the value of the followUpDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFollowUpDate(XMLGregorianCalendar value) {
        this.followUpDate = value;
    }

    /**
     * Gets the value of the regEIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegEIndicator() {
        return regEIndicator;
    }

    /**
     * Sets the value of the regEIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegEIndicator(Boolean value) {
        this.regEIndicator = value;
    }

    /**
     * Gets the value of the regZIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRegZIndicator() {
        return regZIndicator;
    }

    /**
     * Sets the value of the regZIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRegZIndicator(Boolean value) {
        this.regZIndicator = value;
    }

    /**
     * Gets the value of the provisionalCreditIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isProvisionalCreditIndicator() {
        return provisionalCreditIndicator;
    }

    /**
     * Sets the value of the provisionalCreditIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProvisionalCreditIndicator(Boolean value) {
        this.provisionalCreditIndicator = value;
    }

    /**
     * Gets the value of the memberCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCaseNumber() {
        return memberCaseNumber;
    }

    /**
     * Sets the value of the memberCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCaseNumber(String value) {
        this.memberCaseNumber = value;
    }

}
