//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LinkedCaseGroupType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LinkedCaseGroupType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="MANL"/&gt;
 *     &lt;enumeration value="FILING"/&gt;
 *     &lt;enumeration value="SMDSPT"/&gt;
 *     &lt;enumeration value="MCHCBEXT"/&gt;
 *     &lt;enumeration value="MDSPT"/&gt;
 *     &lt;enumeration value="BUNDLE"/&gt;
 *     &lt;enumeration value="MMTCH"/&gt;
 *     &lt;enumeration value="MULTI"/&gt;
 *     &lt;enumeration value="NFFRMLNK"/&gt;
 *     &lt;enumeration value="PAIR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "LinkedCaseGroupType")
@XmlEnum
public enum LinkedCaseGroupType {

    MANL,
    FILING,
    SMDSPT,
    MCHCBEXT,
    MDSPT,
    BUNDLE,
    MMTCH,
    MULTI,
    NFFRMLNK,
    PAIR;

    public String value() {
        return name();
    }

    public static LinkedCaseGroupType fromValue(String v) {
        return valueOf(v);
    }

}
