//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GetAllTransDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetAllTransDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}RolTransactionId"/&gt;
 *         &lt;element name="TransactionDetails" type="{http://www.visa.com/ROLSI}TranDetailsType" minOccurs="0"/&gt;
 *         &lt;element name="MMIDetails" type="{http://www.visa.com/ROLSI}MMIDetailType" minOccurs="0"/&gt;
 *         &lt;element name="AssociatedTransactionList" type="{http://www.visa.com/ROLSI}AssociatedTransactionListType" minOccurs="0"/&gt;
 *         &lt;element name="PurchaseInquiryInformationDetails" type="{http://www.visa.com/ROLSI}PurchaseInquiryInformationDetailsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetAllTransDetailsType", propOrder = {
    "rolTransactionId",
    "transactionDetails",
    "mmiDetails",
    "associatedTransactionList",
    "purchaseInquiryInformationDetails"
})
public class GetAllTransDetailsType {

    @XmlElement(name = "RolTransactionId")
    protected long rolTransactionId;
    @XmlElement(name = "TransactionDetails")
    protected TranDetailsType transactionDetails;
    @XmlElement(name = "MMIDetails")
    protected MMIDetailType mmiDetails;
    @XmlElement(name = "AssociatedTransactionList")
    protected AssociatedTransactionListType associatedTransactionList;
    @XmlElement(name = "PurchaseInquiryInformationDetails")
    protected PurchaseInquiryInformationDetailsType purchaseInquiryInformationDetails;

    /**
     * Gets the value of the rolTransactionId property.
     * 
     */
    public long getRolTransactionId() {
        return rolTransactionId;
    }

    /**
     * Sets the value of the rolTransactionId property.
     * 
     */
    public void setRolTransactionId(long value) {
        this.rolTransactionId = value;
    }

    /**
     * Gets the value of the transactionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TranDetailsType }
     *     
     */
    public TranDetailsType getTransactionDetails() {
        return transactionDetails;
    }

    /**
     * Sets the value of the transactionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranDetailsType }
     *     
     */
    public void setTransactionDetails(TranDetailsType value) {
        this.transactionDetails = value;
    }

    /**
     * Gets the value of the mmiDetails property.
     * 
     * @return
     *     possible object is
     *     {@link MMIDetailType }
     *     
     */
    public MMIDetailType getMMIDetails() {
        return mmiDetails;
    }

    /**
     * Sets the value of the mmiDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link MMIDetailType }
     *     
     */
    public void setMMIDetails(MMIDetailType value) {
        this.mmiDetails = value;
    }

    /**
     * Gets the value of the associatedTransactionList property.
     * 
     * @return
     *     possible object is
     *     {@link AssociatedTransactionListType }
     *     
     */
    public AssociatedTransactionListType getAssociatedTransactionList() {
        return associatedTransactionList;
    }

    /**
     * Sets the value of the associatedTransactionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssociatedTransactionListType }
     *     
     */
    public void setAssociatedTransactionList(AssociatedTransactionListType value) {
        this.associatedTransactionList = value;
    }

    /**
     * Gets the value of the purchaseInquiryInformationDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseInquiryInformationDetailsType }
     *     
     */
    public PurchaseInquiryInformationDetailsType getPurchaseInquiryInformationDetails() {
        return purchaseInquiryInformationDetails;
    }

    /**
     * Sets the value of the purchaseInquiryInformationDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseInquiryInformationDetailsType }
     *     
     */
    public void setPurchaseInquiryInformationDetails(PurchaseInquiryInformationDetailsType value) {
        this.purchaseInquiryInformationDetails = value;
    }

}
