//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Information about a Dispute. It contains a TransactionInfo element and a Create or Submit,PreArb,PreArbResp,DisputeRespond,CaseFiling etc
 * 
 * <p>Java class for DisputeDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisputeDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionInfo" type="{http://www.visa.com/ROLSI}TranHeaderInfoType" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}DisputeDownloadGroup"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeDataType", propOrder = {
    "transactionInfo",
    "dispute",
    "disputeResponse",
    "disputePreArb",
    "disputePreArbResponse",
    "disputeCaseFiling",
    "disputeContactMessage",
    "disputeContactMessageResponse",
    "disputeFinancialAdvice",
    "disputeFinancial",
    "disputePreComp",
    "disputePreCompResponse",
    "acceptanceNotification",
    "disputeFinancialFields"
})
public class DisputeDataType {

    @XmlElement(name = "TransactionInfo")
    protected TranHeaderInfoType transactionInfo;
    @XmlElement(name = "Dispute")
    protected DisputeDetailsType dispute;
    @XmlElement(name = "DisputeResponse")
    protected DisputeResponseDetailsType disputeResponse;
    @XmlElement(name = "DisputePreArb")
    protected DisputePreArbDetailsType disputePreArb;
    @XmlElement(name = "DisputePreArbResponse")
    protected DisputePreArbRespDetailsType disputePreArbResponse;
    @XmlElement(name = "DisputeCaseFiling")
    protected DisputeCaseFilingDetailsType disputeCaseFiling;
    @XmlElement(name = "DisputeContactMessage")
    protected DisputeContactMessageDetailsType disputeContactMessage;
    @XmlElement(name = "DisputeContactMessageResponse")
    protected DisputeContactMessageRespDetailsType disputeContactMessageResponse;
    @XmlElement(name = "DisputeFinancialAdvice")
    protected DisputeFinancialAdviceDetailsType disputeFinancialAdvice;
    @XmlElement(name = "DisputeFinancial")
    protected DisputeFinancialDetailsType disputeFinancial;
    @XmlElement(name = "DisputePreComp")
    protected DisputePreCompDetailsType disputePreComp;
    @XmlElement(name = "DisputePreCompResponse")
    protected DisputePreCompResponseDetailsType disputePreCompResponse;
    @XmlElement(name = "AcceptanceNotification")
    protected AcceptDisputeDetailsType acceptanceNotification;
    @XmlElement(name = "DisputeFinancialFields")
    protected DisputeFinancialFieldsType disputeFinancialFields;

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link TranHeaderInfoType }
     *     
     */
    public TranHeaderInfoType getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranHeaderInfoType }
     *     
     */
    public void setTransactionInfo(TranHeaderInfoType value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the dispute property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeDetailsType }
     *     
     */
    public DisputeDetailsType getDispute() {
        return dispute;
    }

    /**
     * Sets the value of the dispute property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeDetailsType }
     *     
     */
    public void setDispute(DisputeDetailsType value) {
        this.dispute = value;
    }

    /**
     * Gets the value of the disputeResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeResponseDetailsType }
     *     
     */
    public DisputeResponseDetailsType getDisputeResponse() {
        return disputeResponse;
    }

    /**
     * Sets the value of the disputeResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeResponseDetailsType }
     *     
     */
    public void setDisputeResponse(DisputeResponseDetailsType value) {
        this.disputeResponse = value;
    }

    /**
     * Gets the value of the disputePreArb property.
     * 
     * @return
     *     possible object is
     *     {@link DisputePreArbDetailsType }
     *     
     */
    public DisputePreArbDetailsType getDisputePreArb() {
        return disputePreArb;
    }

    /**
     * Sets the value of the disputePreArb property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputePreArbDetailsType }
     *     
     */
    public void setDisputePreArb(DisputePreArbDetailsType value) {
        this.disputePreArb = value;
    }

    /**
     * Gets the value of the disputePreArbResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DisputePreArbRespDetailsType }
     *     
     */
    public DisputePreArbRespDetailsType getDisputePreArbResponse() {
        return disputePreArbResponse;
    }

    /**
     * Sets the value of the disputePreArbResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputePreArbRespDetailsType }
     *     
     */
    public void setDisputePreArbResponse(DisputePreArbRespDetailsType value) {
        this.disputePreArbResponse = value;
    }

    /**
     * Gets the value of the disputeCaseFiling property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeCaseFilingDetailsType }
     *     
     */
    public DisputeCaseFilingDetailsType getDisputeCaseFiling() {
        return disputeCaseFiling;
    }

    /**
     * Sets the value of the disputeCaseFiling property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeCaseFilingDetailsType }
     *     
     */
    public void setDisputeCaseFiling(DisputeCaseFilingDetailsType value) {
        this.disputeCaseFiling = value;
    }

    /**
     * Gets the value of the disputeContactMessage property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeContactMessageDetailsType }
     *     
     */
    public DisputeContactMessageDetailsType getDisputeContactMessage() {
        return disputeContactMessage;
    }

    /**
     * Sets the value of the disputeContactMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeContactMessageDetailsType }
     *     
     */
    public void setDisputeContactMessage(DisputeContactMessageDetailsType value) {
        this.disputeContactMessage = value;
    }

    /**
     * Gets the value of the disputeContactMessageResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeContactMessageRespDetailsType }
     *     
     */
    public DisputeContactMessageRespDetailsType getDisputeContactMessageResponse() {
        return disputeContactMessageResponse;
    }

    /**
     * Sets the value of the disputeContactMessageResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeContactMessageRespDetailsType }
     *     
     */
    public void setDisputeContactMessageResponse(DisputeContactMessageRespDetailsType value) {
        this.disputeContactMessageResponse = value;
    }

    /**
     * Gets the value of the disputeFinancialAdvice property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeFinancialAdviceDetailsType }
     *     
     */
    public DisputeFinancialAdviceDetailsType getDisputeFinancialAdvice() {
        return disputeFinancialAdvice;
    }

    /**
     * Sets the value of the disputeFinancialAdvice property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeFinancialAdviceDetailsType }
     *     
     */
    public void setDisputeFinancialAdvice(DisputeFinancialAdviceDetailsType value) {
        this.disputeFinancialAdvice = value;
    }

    /**
     * Gets the value of the disputeFinancial property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeFinancialDetailsType }
     *     
     */
    public DisputeFinancialDetailsType getDisputeFinancial() {
        return disputeFinancial;
    }

    /**
     * Sets the value of the disputeFinancial property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeFinancialDetailsType }
     *     
     */
    public void setDisputeFinancial(DisputeFinancialDetailsType value) {
        this.disputeFinancial = value;
    }

    /**
     * Gets the value of the disputePreComp property.
     * 
     * @return
     *     possible object is
     *     {@link DisputePreCompDetailsType }
     *     
     */
    public DisputePreCompDetailsType getDisputePreComp() {
        return disputePreComp;
    }

    /**
     * Sets the value of the disputePreComp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputePreCompDetailsType }
     *     
     */
    public void setDisputePreComp(DisputePreCompDetailsType value) {
        this.disputePreComp = value;
    }

    /**
     * Gets the value of the disputePreCompResponse property.
     * 
     * @return
     *     possible object is
     *     {@link DisputePreCompResponseDetailsType }
     *     
     */
    public DisputePreCompResponseDetailsType getDisputePreCompResponse() {
        return disputePreCompResponse;
    }

    /**
     * Sets the value of the disputePreCompResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputePreCompResponseDetailsType }
     *     
     */
    public void setDisputePreCompResponse(DisputePreCompResponseDetailsType value) {
        this.disputePreCompResponse = value;
    }

    /**
     * Gets the value of the acceptanceNotification property.
     * 
     * @return
     *     possible object is
     *     {@link AcceptDisputeDetailsType }
     *     
     */
    public AcceptDisputeDetailsType getAcceptanceNotification() {
        return acceptanceNotification;
    }

    /**
     * Sets the value of the acceptanceNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcceptDisputeDetailsType }
     *     
     */
    public void setAcceptanceNotification(AcceptDisputeDetailsType value) {
        this.acceptanceNotification = value;
    }

    /**
     * Gets the value of the disputeFinancialFields property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeFinancialFieldsType }
     *     
     */
    public DisputeFinancialFieldsType getDisputeFinancialFields() {
        return disputeFinancialFields;
    }

    /**
     * Sets the value of the disputeFinancialFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeFinancialFieldsType }
     *     
     */
    public void setDisputeFinancialFields(DisputeFinancialFieldsType value) {
        this.disputeFinancialFields = value;
    }

}
