//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IgnoreRejectResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IgnoreRejectResponseBodyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IgnoreRejectResponse" type="{http://www.visa.com/ROLSI}IgnoreRejectResponseType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IgnoreRejectResponseBodyType", propOrder = {
    "ignoreRejectResponse"
})
public class IgnoreRejectResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "IgnoreRejectResponse", required = true)
    protected IgnoreRejectResponseType ignoreRejectResponse;

    /**
     * Gets the value of the ignoreRejectResponse property.
     * 
     * @return
     *     possible object is
     *     {@link IgnoreRejectResponseType }
     *     
     */
    public IgnoreRejectResponseType getIgnoreRejectResponse() {
        return ignoreRejectResponse;
    }

    /**
     * Sets the value of the ignoreRejectResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link IgnoreRejectResponseType }
     *     
     */
    public void setIgnoreRejectResponse(IgnoreRejectResponseType value) {
        this.ignoreRejectResponse = value;
    }

}
