//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import org.codehaus.jackson.annotate.JsonCreator;
import org.codehaus.jackson.annotate.JsonValue;


/**
 * <p>Java class for RTSIQnActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RTSIQnActionType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Pend"/&gt;
 *     &lt;enumeration value="Submit"/&gt;
 *     &lt;enumeration value="SubmitForReview"/&gt;
 *     &lt;enumeration value="Delete"/&gt;
 *     &lt;enumeration value="ForcePost"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RTSIQnActionType")
@XmlEnum
public enum RTSIQnActionType {

    @XmlEnumValue("Pend")
    PEND("Pend"),
    @XmlEnumValue("Submit")
    SUBMIT("Submit"),
    @XmlEnumValue("SubmitForReview")
    SUBMIT_FOR_REVIEW("SubmitForReview"),
    @XmlEnumValue("Delete")
    DELETE("Delete"),
    @XmlEnumValue("ForcePost")
    FORCE_POST("ForcePost");
    private final String value;

    RTSIQnActionType(String v) {
        value = v;
    }
    
    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static RTSIQnActionType fromValue(String v) {
        for (RTSIQnActionType c: RTSIQnActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
