//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InitiatePreCompFromTransactionOrCaseResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InitiatePreCompFromTransactionOrCaseResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}VisaCaseNumber" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}DisputePreCompId" minOccurs="0"/&gt;
 *         &lt;element name="AEMInd" type="{http://www.visa.com/ROLSI}AEMIndType" minOccurs="0"/&gt;
 *         &lt;element name="ATRSelectionReqdInd" type="{http://www.visa.com/ROLSI}ATRSelectionReqdIndType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}AssociatedTransGroupId" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InitiatePreCompFromTransactionOrCaseResponseType", propOrder = {
    "visaCaseNumber",
    "disputePreCompId",
    "aemInd",
    "atrSelectionReqdInd",
    "associatedTransGroupId"
})
public class InitiatePreCompFromTransactionOrCaseResponseType {

    @XmlElement(name = "VisaCaseNumber")
    protected Long visaCaseNumber;
    @XmlElement(name = "DisputePreCompId")
    protected Long disputePreCompId;
    @XmlElement(name = "AEMInd")
    @XmlSchemaType(name = "string")
    protected AEMIndType aemInd;
    @XmlElement(name = "ATRSelectionReqdInd")
    @XmlSchemaType(name = "string")
    protected ATRSelectionReqdIndType atrSelectionReqdInd;
    @XmlElement(name = "AssociatedTransGroupId")
    protected Long associatedTransGroupId;

    /**
     * Gets the value of the visaCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVisaCaseNumber() {
        return visaCaseNumber;
    }

    /**
     * Sets the value of the visaCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVisaCaseNumber(Long value) {
        this.visaCaseNumber = value;
    }

    /**
     * Gets the value of the disputePreCompId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDisputePreCompId() {
        return disputePreCompId;
    }

    /**
     * Sets the value of the disputePreCompId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDisputePreCompId(Long value) {
        this.disputePreCompId = value;
    }

    /**
     * Gets the value of the aemInd property.
     * 
     * @return
     *     possible object is
     *     {@link AEMIndType }
     *     
     */
    public AEMIndType getAEMInd() {
        return aemInd;
    }

    /**
     * Sets the value of the aemInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link AEMIndType }
     *     
     */
    public void setAEMInd(AEMIndType value) {
        this.aemInd = value;
    }

    /**
     * Gets the value of the atrSelectionReqdInd property.
     * 
     * @return
     *     possible object is
     *     {@link ATRSelectionReqdIndType }
     *     
     */
    public ATRSelectionReqdIndType getATRSelectionReqdInd() {
        return atrSelectionReqdInd;
    }

    /**
     * Sets the value of the atrSelectionReqdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ATRSelectionReqdIndType }
     *     
     */
    public void setATRSelectionReqdInd(ATRSelectionReqdIndType value) {
        this.atrSelectionReqdInd = value;
    }

    /**
     * Gets the value of the associatedTransGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAssociatedTransGroupId() {
        return associatedTransGroupId;
    }

    /**
     * Sets the value of the associatedTransGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAssociatedTransGroupId(Long value) {
        this.associatedTransGroupId = value;
    }

}
