//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DisputeFinancialInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DisputeFinancialInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VROLFinancialSentInd" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}VROLFinancialID" minOccurs="0"/&gt;
 *         &lt;element name="FinancialTransactionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FinancialAmt" type="{http://www.visa.com/ROLSI}AmountType" minOccurs="0"/&gt;
 *         &lt;element name="DisputeCategory" type="{http://www.visa.com/ROLSI}DisputeCategoryType" minOccurs="0"/&gt;
 *         &lt;element name="DisputeCondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}DisputeId" minOccurs="0"/&gt;
 *         &lt;element name="VROLBundleCaseNumber" type="{http://www.visa.com/ROLSI}VisaCaseNumberType" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}TransactionID" minOccurs="0"/&gt;
 *         &lt;element name="IssuerCaseNumber" type="{http://www.visa.com/ROLSI}MemberCaseNumberType" minOccurs="0"/&gt;
 *         &lt;element name="AcquirerCaseNumber" type="{http://www.visa.com/ROLSI}MemberCaseNumberType" minOccurs="0"/&gt;
 *         &lt;element name="OpposerExpectedRespDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DisputeFinancialInformationType", propOrder = {
    "vrolFinancialSentInd",
    "vrolFinancialID",
    "financialTransactionType",
    "financialAmt",
    "disputeCategory",
    "disputeCondition",
    "disputeId",
    "vrolBundleCaseNumber",
    "transactionID",
    "issuerCaseNumber",
    "acquirerCaseNumber",
    "opposerExpectedRespDate"
})
public class DisputeFinancialInformationType {

    @XmlElement(name = "VROLFinancialSentInd")
    protected Boolean vrolFinancialSentInd;
    @XmlElement(name = "VROLFinancialID")
    protected String vrolFinancialID;
    @XmlElement(name = "FinancialTransactionType")
    protected String financialTransactionType;
    @XmlElement(name = "FinancialAmt")
    protected AmountType financialAmt;
    @XmlElement(name = "DisputeCategory")
    protected DisputeCategoryType disputeCategory;
    @XmlElement(name = "DisputeCondition")
    protected String disputeCondition;
    @XmlElement(name = "DisputeId")
    protected Long disputeId;
    @XmlElement(name = "VROLBundleCaseNumber")
    protected Long vrolBundleCaseNumber;
    @XmlElement(name = "TransactionID")
    protected String transactionID;
    @XmlElement(name = "IssuerCaseNumber")
    protected String issuerCaseNumber;
    @XmlElement(name = "AcquirerCaseNumber")
    protected String acquirerCaseNumber;
    @XmlElement(name = "OpposerExpectedRespDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar opposerExpectedRespDate;

    /**
     * Gets the value of the vrolFinancialSentInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isVROLFinancialSentInd() {
        return vrolFinancialSentInd;
    }

    /**
     * Sets the value of the vrolFinancialSentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVROLFinancialSentInd(Boolean value) {
        this.vrolFinancialSentInd = value;
    }

    /**
     * Gets the value of the vrolFinancialID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVROLFinancialID() {
        return vrolFinancialID;
    }

    /**
     * Sets the value of the vrolFinancialID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVROLFinancialID(String value) {
        this.vrolFinancialID = value;
    }

    /**
     * Gets the value of the financialTransactionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancialTransactionType() {
        return financialTransactionType;
    }

    /**
     * Sets the value of the financialTransactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancialTransactionType(String value) {
        this.financialTransactionType = value;
    }

    /**
     * Gets the value of the financialAmt property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getFinancialAmt() {
        return financialAmt;
    }

    /**
     * Sets the value of the financialAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setFinancialAmt(AmountType value) {
        this.financialAmt = value;
    }

    /**
     * Gets the value of the disputeCategory property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeCategoryType }
     *     
     */
    public DisputeCategoryType getDisputeCategory() {
        return disputeCategory;
    }

    /**
     * Sets the value of the disputeCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeCategoryType }
     *     
     */
    public void setDisputeCategory(DisputeCategoryType value) {
        this.disputeCategory = value;
    }

    /**
     * Gets the value of the disputeCondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCondition() {
        return disputeCondition;
    }

    /**
     * Sets the value of the disputeCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCondition(String value) {
        this.disputeCondition = value;
    }

    /**
     * Gets the value of the disputeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDisputeId() {
        return disputeId;
    }

    /**
     * Sets the value of the disputeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDisputeId(Long value) {
        this.disputeId = value;
    }

    /**
     * Gets the value of the vrolBundleCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getVROLBundleCaseNumber() {
        return vrolBundleCaseNumber;
    }

    /**
     * Sets the value of the vrolBundleCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setVROLBundleCaseNumber(Long value) {
        this.vrolBundleCaseNumber = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the issuerCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuerCaseNumber() {
        return issuerCaseNumber;
    }

    /**
     * Sets the value of the issuerCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuerCaseNumber(String value) {
        this.issuerCaseNumber = value;
    }

    /**
     * Gets the value of the acquirerCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquirerCaseNumber() {
        return acquirerCaseNumber;
    }

    /**
     * Sets the value of the acquirerCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquirerCaseNumber(String value) {
        this.acquirerCaseNumber = value;
    }

    /**
     * Gets the value of the opposerExpectedRespDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOpposerExpectedRespDate() {
        return opposerExpectedRespDate;
    }

    /**
     * Sets the value of the opposerExpectedRespDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOpposerExpectedRespDate(XMLGregorianCalendar value) {
        this.opposerExpectedRespDate = value;
    }

}
