//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * @direction: Response
 * 
 * <p>Java class for CaseManifestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseManifestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="User" type="{http://www.visa.com/ROLSI}UserType" minOccurs="0"/&gt;
 *         &lt;element name="Case" type="{http://www.visa.com/ROLSI}CaseSummaryInfoType"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}Image" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;choice minOccurs="0"&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}QuestionnaireData" minOccurs="0"/&gt;
 *           &lt;element name="FinancialData" type="{http://www.visa.com/ROLSI}FnDataType" minOccurs="0"/&gt;
 *           &lt;element name="RFCData" type="{http://www.visa.com/ROLSI}RFCDataType" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}FilingData" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}ChargebackRepresentmentAdviceData" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}FraudData" minOccurs="0"/&gt;
 *           &lt;element ref="{http://www.visa.com/ROLSI}QuickFormData" minOccurs="0"/&gt;
 *           &lt;element name="MessageData" type="{http://www.visa.com/ROLSI}MessageDataType" minOccurs="0"/&gt;
 *           &lt;element name="CollaborationData" type="{http://www.visa.com/ROLSI}CollabDataType" minOccurs="0"/&gt;
 *           &lt;element name="DisputeData" type="{http://www.visa.com/ROLSI}DisputeDataType" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="memberRole" type="{http://www.visa.com/ROLSI}MemberRoleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseManifestType", propOrder = {
    "user",
    "_case",
    "image",
    "questionnaireData",
    "financialData",
    "rfcData",
    "filingData",
    "chargebackRepresentmentAdviceData",
    "fraudData",
    "quickFormData",
    "messageData",
    "collaborationData",
    "disputeData"
})
public class CaseManifestType {

    @XmlElement(name = "User")
    protected UserType user;
    @XmlElement(name = "Case", required = true)
    protected CaseSummaryInfoType _case;
    @XmlElement(name = "Image")
    protected List<ImageType> image;
    @XmlElement(name = "QuestionnaireData")
    protected QnDataType questionnaireData;
    @XmlElement(name = "FinancialData")
    protected FnDataType financialData;
    @XmlElement(name = "RFCData")
    protected RFCDataType rfcData;
    @XmlElement(name = "FilingData")
    protected CaseFilingFormDataType filingData;
    @XmlElement(name = "ChargebackRepresentmentAdviceData")
    protected CBRepreAdviceDataType chargebackRepresentmentAdviceData;
    @XmlElement(name = "FraudData")
    protected FraudDataType fraudData;
    @XmlElement(name = "QuickFormData")
    protected QuickFormDataType quickFormData;
    @XmlElement(name = "MessageData")
    protected MessageDataType messageData;
    @XmlElement(name = "CollaborationData")
    protected CollabDataType collaborationData;
    @XmlElement(name = "DisputeData")
    protected DisputeDataType disputeData;
    @XmlAttribute(name = "memberRole")
    protected MemberRoleType memberRole;

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the case property.
     * 
     * @return
     *     possible object is
     *     {@link CaseSummaryInfoType }
     *     
     */
    public CaseSummaryInfoType getCase() {
        return _case;
    }

    /**
     * Sets the value of the case property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseSummaryInfoType }
     *     
     */
    public void setCase(CaseSummaryInfoType value) {
        this._case = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the image property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ImageType }
     * 
     * 
     */
    public List<ImageType> getImage() {
        if (image == null) {
            image = new ArrayList<ImageType>();
        }
        return this.image;
    }

    /**
     * @description: Contains details about the active questionnaire on the case.
     * 
     * @return
     *     possible object is
     *     {@link QnDataType }
     *     
     */
    public QnDataType getQuestionnaireData() {
        return questionnaireData;
    }

    /**
     * Sets the value of the questionnaireData property.
     * 
     * @param value
     *     allowed object is
     *     {@link QnDataType }
     *     
     */
    public void setQuestionnaireData(QnDataType value) {
        this.questionnaireData = value;
    }

    /**
     * Gets the value of the financialData property.
     * 
     * @return
     *     possible object is
     *     {@link FnDataType }
     *     
     */
    public FnDataType getFinancialData() {
        return financialData;
    }

    /**
     * Sets the value of the financialData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FnDataType }
     *     
     */
    public void setFinancialData(FnDataType value) {
        this.financialData = value;
    }

    /**
     * Gets the value of the rfcData property.
     * 
     * @return
     *     possible object is
     *     {@link RFCDataType }
     *     
     */
    public RFCDataType getRFCData() {
        return rfcData;
    }

    /**
     * Sets the value of the rfcData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RFCDataType }
     *     
     */
    public void setRFCData(RFCDataType value) {
        this.rfcData = value;
    }

    /**
     * Gets the value of the filingData property.
     * 
     * @return
     *     possible object is
     *     {@link CaseFilingFormDataType }
     *     
     */
    public CaseFilingFormDataType getFilingData() {
        return filingData;
    }

    /**
     * Sets the value of the filingData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseFilingFormDataType }
     *     
     */
    public void setFilingData(CaseFilingFormDataType value) {
        this.filingData = value;
    }

    /**
     * Gets the value of the chargebackRepresentmentAdviceData property.
     * 
     * @return
     *     possible object is
     *     {@link CBRepreAdviceDataType }
     *     
     */
    public CBRepreAdviceDataType getChargebackRepresentmentAdviceData() {
        return chargebackRepresentmentAdviceData;
    }

    /**
     * Sets the value of the chargebackRepresentmentAdviceData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CBRepreAdviceDataType }
     *     
     */
    public void setChargebackRepresentmentAdviceData(CBRepreAdviceDataType value) {
        this.chargebackRepresentmentAdviceData = value;
    }

    /**
     * Gets the value of the fraudData property.
     * 
     * @return
     *     possible object is
     *     {@link FraudDataType }
     *     
     */
    public FraudDataType getFraudData() {
        return fraudData;
    }

    /**
     * Sets the value of the fraudData property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudDataType }
     *     
     */
    public void setFraudData(FraudDataType value) {
        this.fraudData = value;
    }

    /**
     * Gets the value of the quickFormData property.
     * 
     * @return
     *     possible object is
     *     {@link QuickFormDataType }
     *     
     */
    public QuickFormDataType getQuickFormData() {
        return quickFormData;
    }

    /**
     * Sets the value of the quickFormData property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuickFormDataType }
     *     
     */
    public void setQuickFormData(QuickFormDataType value) {
        this.quickFormData = value;
    }

    /**
     * Gets the value of the messageData property.
     * 
     * @return
     *     possible object is
     *     {@link MessageDataType }
     *     
     */
    public MessageDataType getMessageData() {
        return messageData;
    }

    /**
     * Sets the value of the messageData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageDataType }
     *     
     */
    public void setMessageData(MessageDataType value) {
        this.messageData = value;
    }

    /**
     * Gets the value of the collaborationData property.
     * 
     * @return
     *     possible object is
     *     {@link CollabDataType }
     *     
     */
    public CollabDataType getCollaborationData() {
        return collaborationData;
    }

    /**
     * Sets the value of the collaborationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollabDataType }
     *     
     */
    public void setCollaborationData(CollabDataType value) {
        this.collaborationData = value;
    }

    /**
     * Gets the value of the disputeData property.
     * 
     * @return
     *     possible object is
     *     {@link DisputeDataType }
     *     
     */
    public DisputeDataType getDisputeData() {
        return disputeData;
    }

    /**
     * Sets the value of the disputeData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisputeDataType }
     *     
     */
    public void setDisputeData(DisputeDataType value) {
        this.disputeData = value;
    }

    /**
     * Gets the value of the memberRole property.
     * 
     * @return
     *     possible object is
     *     {@link MemberRoleType }
     *     
     */
    public MemberRoleType getMemberRole() {
        return memberRole;
    }

    /**
     * Sets the value of the memberRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberRoleType }
     *     
     */
    public void setMemberRole(MemberRoleType value) {
        this.memberRole = value;
    }

}
