//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QnTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QnTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CB"/&gt;
 *     &lt;enumeration value="REP"/&gt;
 *     &lt;enumeration value="GF"/&gt;
 *     &lt;enumeration value="GFR"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PAR"/&gt;
 *     &lt;enumeration value="PC"/&gt;
 *     &lt;enumeration value="PCR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QnTypeType")
@XmlEnum
public enum QnTypeType {

    CB,
    REP,
    GF,
    GFR,
    PA,
    PAR,
    PC,
    PCR;

    public String value() {
        return name();
    }

    public static QnTypeType fromValue(String v) {
        return valueOf(v);
    }

}
