//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PreCompRespDisputeOnlyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreCompRespDisputeOnlyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}PreCompBaseDisputeGroup"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}PreFilingBaseGroup"/&gt;
 *         &lt;element name="ViolationOrDiscoveryDateFromTranCpd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.visa.com/ROLSI}PreFilingRespGroup"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreCompRespDisputeOnlyType", propOrder = {
    "disputeRuleSetCode",
    "disputeAmt",
    "additionalInfoComments",
    "contactAddress",
    "contactBestTimeToCall",
    "contactCity",
    "contactCountryCode",
    "contactEmail",
    "contactFax",
    "contactName",
    "contactOptInInd",
    "contactPhone",
    "contactPostalCode",
    "contactStateCode",
    "daysToRespond",
    "lastDayToRespond",
    "initiatePreFilingReason",
    "initiatorEmail",
    "initiatorFax",
    "initiatorName",
    "initiatorPhone",
    "memberCaseNumber",
    "merchantURL",
    "recallInd",
    "recallReason",
    "violationOrDiscoveryDateFromTranCpd",
    "acceptanceAmount",
    "continuePreFilingReason",
    "partialAcceptanceReason",
    "responseCode",
    "whenAmountSentDate",
    "transferFundsNowCd"
})
public class PreCompRespDisputeOnlyType {

    @XmlElement(name = "DisputeRuleSetCode")
    @XmlSchemaType(name = "string")
    protected RuleSetCodeType disputeRuleSetCode;
    @XmlElement(name = "DisputeAmt")
    protected AmountType disputeAmt;
    @XmlElement(name = "AdditionalInfoComments")
    protected String additionalInfoComments;
    @XmlElement(name = "ContactAddress")
    protected String contactAddress;
    @XmlElement(name = "ContactBestTimeToCall")
    protected String contactBestTimeToCall;
    @XmlElement(name = "ContactCity")
    protected String contactCity;
    @XmlElement(name = "ContactCountryCode")
    protected String contactCountryCode;
    @XmlElement(name = "ContactEmail")
    protected String contactEmail;
    @XmlElement(name = "ContactFax")
    protected String contactFax;
    @XmlElement(name = "ContactName")
    protected String contactName;
    @XmlElement(name = "ContactOptInInd")
    protected Boolean contactOptInInd;
    @XmlElement(name = "ContactPhone")
    protected String contactPhone;
    @XmlElement(name = "ContactPostalCode")
    protected String contactPostalCode;
    @XmlElement(name = "ContactStateCode")
    protected String contactStateCode;
    @XmlElement(name = "DaysToRespond")
    protected Integer daysToRespond;
    @XmlElement(name = "LastDayToRespond")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastDayToRespond;
    @XmlElement(name = "InitiatePreFilingReason")
    protected String initiatePreFilingReason;
    @XmlElement(name = "InitiatorEmail")
    protected String initiatorEmail;
    @XmlElement(name = "InitiatorFax")
    protected String initiatorFax;
    @XmlElement(name = "InitiatorName")
    protected String initiatorName;
    @XmlElement(name = "InitiatorPhone")
    protected String initiatorPhone;
    @XmlElement(name = "MemberCaseNumber")
    protected String memberCaseNumber;
    @XmlElement(name = "MerchantURL")
    protected String merchantURL;
    @XmlElement(name = "RecallInd")
    protected Boolean recallInd;
    @XmlElement(name = "RecallReason")
    protected String recallReason;
    @XmlElement(name = "ViolationOrDiscoveryDateFromTranCpd")
    protected String violationOrDiscoveryDateFromTranCpd;
    @XmlElement(name = "AcceptanceAmount")
    protected AmountType acceptanceAmount;
    @XmlElement(name = "ContinuePreFilingReason")
    protected String continuePreFilingReason;
    @XmlElement(name = "PartialAcceptanceReason")
    protected String partialAcceptanceReason;
    @XmlElement(name = "ResponseCode")
    protected String responseCode;
    @XmlElement(name = "WhenAmountSentDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar whenAmountSentDate;
    @XmlElement(name = "TransferFundsNowCd")
    @XmlSchemaType(name = "string")
    protected YNType transferFundsNowCd;

    /**
     * Note: No longer used by VROL
     * 
     * @return
     *     possible object is
     *     {@link RuleSetCodeType }
     *     
     */
    public RuleSetCodeType getDisputeRuleSetCode() {
        return disputeRuleSetCode;
    }

    /**
     * Sets the value of the disputeRuleSetCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuleSetCodeType }
     *     
     */
    public void setDisputeRuleSetCode(RuleSetCodeType value) {
        this.disputeRuleSetCode = value;
    }

    /**
     * Gets the value of the disputeAmt property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getDisputeAmt() {
        return disputeAmt;
    }

    /**
     * Sets the value of the disputeAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setDisputeAmt(AmountType value) {
        this.disputeAmt = value;
    }

    /**
     * Gets the value of the additionalInfoComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfoComments() {
        return additionalInfoComments;
    }

    /**
     * Sets the value of the additionalInfoComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfoComments(String value) {
        this.additionalInfoComments = value;
    }

    /**
     * Gets the value of the contactAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * Sets the value of the contactAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactAddress(String value) {
        this.contactAddress = value;
    }

    /**
     * Gets the value of the contactBestTimeToCall property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactBestTimeToCall() {
        return contactBestTimeToCall;
    }

    /**
     * Sets the value of the contactBestTimeToCall property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactBestTimeToCall(String value) {
        this.contactBestTimeToCall = value;
    }

    /**
     * Gets the value of the contactCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCity() {
        return contactCity;
    }

    /**
     * Sets the value of the contactCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCity(String value) {
        this.contactCity = value;
    }

    /**
     * Gets the value of the contactCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactCountryCode() {
        return contactCountryCode;
    }

    /**
     * Sets the value of the contactCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactCountryCode(String value) {
        this.contactCountryCode = value;
    }

    /**
     * Gets the value of the contactEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * Sets the value of the contactEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactEmail(String value) {
        this.contactEmail = value;
    }

    /**
     * Gets the value of the contactFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactFax() {
        return contactFax;
    }

    /**
     * Sets the value of the contactFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactFax(String value) {
        this.contactFax = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the contactOptInInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContactOptInInd() {
        return contactOptInInd;
    }

    /**
     * Sets the value of the contactOptInInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContactOptInInd(Boolean value) {
        this.contactOptInInd = value;
    }

    /**
     * Gets the value of the contactPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * Sets the value of the contactPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPhone(String value) {
        this.contactPhone = value;
    }

    /**
     * Gets the value of the contactPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactPostalCode() {
        return contactPostalCode;
    }

    /**
     * Sets the value of the contactPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactPostalCode(String value) {
        this.contactPostalCode = value;
    }

    /**
     * Gets the value of the contactStateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactStateCode() {
        return contactStateCode;
    }

    /**
     * Sets the value of the contactStateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactStateCode(String value) {
        this.contactStateCode = value;
    }

    /**
     * Gets the value of the daysToRespond property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDaysToRespond() {
        return daysToRespond;
    }

    /**
     * Sets the value of the daysToRespond property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDaysToRespond(Integer value) {
        this.daysToRespond = value;
    }

    /**
     * Gets the value of the lastDayToRespond property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastDayToRespond() {
        return lastDayToRespond;
    }

    /**
     * Sets the value of the lastDayToRespond property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastDayToRespond(XMLGregorianCalendar value) {
        this.lastDayToRespond = value;
    }

    /**
     * Gets the value of the initiatePreFilingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatePreFilingReason() {
        return initiatePreFilingReason;
    }

    /**
     * Sets the value of the initiatePreFilingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatePreFilingReason(String value) {
        this.initiatePreFilingReason = value;
    }

    /**
     * Gets the value of the initiatorEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorEmail() {
        return initiatorEmail;
    }

    /**
     * Sets the value of the initiatorEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorEmail(String value) {
        this.initiatorEmail = value;
    }

    /**
     * Gets the value of the initiatorFax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorFax() {
        return initiatorFax;
    }

    /**
     * Sets the value of the initiatorFax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorFax(String value) {
        this.initiatorFax = value;
    }

    /**
     * Gets the value of the initiatorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorName() {
        return initiatorName;
    }

    /**
     * Sets the value of the initiatorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorName(String value) {
        this.initiatorName = value;
    }

    /**
     * Gets the value of the initiatorPhone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitiatorPhone() {
        return initiatorPhone;
    }

    /**
     * Sets the value of the initiatorPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitiatorPhone(String value) {
        this.initiatorPhone = value;
    }

    /**
     * Gets the value of the memberCaseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberCaseNumber() {
        return memberCaseNumber;
    }

    /**
     * Sets the value of the memberCaseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberCaseNumber(String value) {
        this.memberCaseNumber = value;
    }

    /**
     * Gets the value of the merchantURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchantURL() {
        return merchantURL;
    }

    /**
     * Sets the value of the merchantURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchantURL(String value) {
        this.merchantURL = value;
    }

    /**
     * Gets the value of the recallInd property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRecallInd() {
        return recallInd;
    }

    /**
     * Sets the value of the recallInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRecallInd(Boolean value) {
        this.recallInd = value;
    }

    /**
     * Gets the value of the recallReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecallReason() {
        return recallReason;
    }

    /**
     * Sets the value of the recallReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecallReason(String value) {
        this.recallReason = value;
    }

    /**
     * Gets the value of the violationOrDiscoveryDateFromTranCpd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViolationOrDiscoveryDateFromTranCpd() {
        return violationOrDiscoveryDateFromTranCpd;
    }

    /**
     * Sets the value of the violationOrDiscoveryDateFromTranCpd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViolationOrDiscoveryDateFromTranCpd(String value) {
        this.violationOrDiscoveryDateFromTranCpd = value;
    }

    /**
     * Gets the value of the acceptanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getAcceptanceAmount() {
        return acceptanceAmount;
    }

    /**
     * Sets the value of the acceptanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setAcceptanceAmount(AmountType value) {
        this.acceptanceAmount = value;
    }

    /**
     * Gets the value of the continuePreFilingReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinuePreFilingReason() {
        return continuePreFilingReason;
    }

    /**
     * Sets the value of the continuePreFilingReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinuePreFilingReason(String value) {
        this.continuePreFilingReason = value;
    }

    /**
     * Gets the value of the partialAcceptanceReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialAcceptanceReason() {
        return partialAcceptanceReason;
    }

    /**
     * Sets the value of the partialAcceptanceReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialAcceptanceReason(String value) {
        this.partialAcceptanceReason = value;
    }

    /**
     * Gets the value of the responseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponseCode() {
        return responseCode;
    }

    /**
     * Sets the value of the responseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponseCode(String value) {
        this.responseCode = value;
    }

    /**
     * Gets the value of the whenAmountSentDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWhenAmountSentDate() {
        return whenAmountSentDate;
    }

    /**
     * Sets the value of the whenAmountSentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWhenAmountSentDate(XMLGregorianCalendar value) {
        this.whenAmountSentDate = value;
    }

    /**
     * Gets the value of the transferFundsNowCd property.
     * 
     * @return
     *     possible object is
     *     {@link YNType }
     *     
     */
    public YNType getTransferFundsNowCd() {
        return transferFundsNowCd;
    }

    /**
     * Sets the value of the transferFundsNowCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link YNType }
     *     
     */
    public void setTransferFundsNowCd(YNType value) {
        this.transferFundsNowCd = value;
    }

}
