//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MiscFeeDetailsResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MiscFeeDetailsResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}VisaCaseNumber"/&gt;
 *         &lt;element name="MiscFeeID" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}MiscellaneousFee"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}SwitchingSystemStatus" maxOccurs="6" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MiscFeeDetailsResponseType", propOrder = {
    "visaCaseNumber",
    "miscFeeID",
    "miscellaneousFee",
    "switchingSystemStatus"
})
public class MiscFeeDetailsResponseType {

    @XmlElement(name = "VisaCaseNumber")
    protected long visaCaseNumber;
    @XmlElement(name = "MiscFeeID")
    protected long miscFeeID;
    @XmlElement(name = "MiscellaneousFee", required = true)
    protected MiscFeeType miscellaneousFee;
    @XmlElement(name = "SwitchingSystemStatus")
    protected List<SwitchingSystemStatusType> switchingSystemStatus;

    /**
     * Gets the value of the visaCaseNumber property.
     * 
     */
    public long getVisaCaseNumber() {
        return visaCaseNumber;
    }

    /**
     * Sets the value of the visaCaseNumber property.
     * 
     */
    public void setVisaCaseNumber(long value) {
        this.visaCaseNumber = value;
    }

    /**
     * Gets the value of the miscFeeID property.
     * 
     */
    public long getMiscFeeID() {
        return miscFeeID;
    }

    /**
     * Sets the value of the miscFeeID property.
     * 
     */
    public void setMiscFeeID(long value) {
        this.miscFeeID = value;
    }

    /**
     * Gets the value of the miscellaneousFee property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeType }
     *     
     */
    public MiscFeeType getMiscellaneousFee() {
        return miscellaneousFee;
    }

    /**
     * Sets the value of the miscellaneousFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeType }
     *     
     */
    public void setMiscellaneousFee(MiscFeeType value) {
        this.miscellaneousFee = value;
    }

    /**
     * Gets the value of the switchingSystemStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the switchingSystemStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSwitchingSystemStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SwitchingSystemStatusType }
     * 
     * 
     */
    public List<SwitchingSystemStatusType> getSwitchingSystemStatus() {
        if (switchingSystemStatus == null) {
            switchingSystemStatus = new ArrayList<SwitchingSystemStatusType>();
        }
        return this.switchingSystemStatus;
    }

}
