//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionFileIdentiferType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExceptionFileIdentiferType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ExceptionFileID" type="{http://www.visa.com/ROLSI}ExceptionFileIDType" minOccurs="0"/&gt;
 *         &lt;element name="ExceptionFileType" type="{http://www.visa.com/ROLSI}ExceptionFileListingType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionFileIdentiferType", propOrder = {
    "exceptionFileID",
    "exceptionFileType"
})
public class ExceptionFileIdentiferType {

    @XmlElement(name = "ExceptionFileID")
    protected ExceptionFileIDType exceptionFileID;
    @XmlElement(name = "ExceptionFileType")
    @XmlSchemaType(name = "string")
    protected ExceptionFileListingType exceptionFileType;

    /**
     * Gets the value of the exceptionFileID property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionFileIDType }
     *     
     */
    public ExceptionFileIDType getExceptionFileID() {
        return exceptionFileID;
    }

    /**
     * Sets the value of the exceptionFileID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionFileIDType }
     *     
     */
    public void setExceptionFileID(ExceptionFileIDType value) {
        this.exceptionFileID = value;
    }

    /**
     * Gets the value of the exceptionFileType property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionFileListingType }
     *     
     */
    public ExceptionFileListingType getExceptionFileType() {
        return exceptionFileType;
    }

    /**
     * Sets the value of the exceptionFileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionFileListingType }
     *     
     */
    public void setExceptionFileType(ExceptionFileListingType value) {
        this.exceptionFileType = value;
    }

}
