//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MiscFeeIndicatorsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MiscFeeIndicatorsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MiscFeeID" type="{http://www.visa.com/ROLSI}MiscFeeIDType" minOccurs="0"/&gt;
 *         &lt;element name="MiscFeeType" type="{http://www.visa.com/ROLSI}MiscFeeTypeCode" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.visa.com/ROLSI}Direction" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MiscFeeIndicatorsType", propOrder = {
    "miscFeeID",
    "miscFeeType",
    "direction"
})
public class MiscFeeIndicatorsType {

    @XmlElement(name = "MiscFeeID")
    protected MiscFeeIDType miscFeeID;
    @XmlElement(name = "MiscFeeType")
    @XmlSchemaType(name = "string")
    protected MiscFeeTypeCode miscFeeType;
    @XmlElement(name = "Direction")
    protected String direction;

    /**
     * Gets the value of the miscFeeID property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeIDType }
     *     
     */
    public MiscFeeIDType getMiscFeeID() {
        return miscFeeID;
    }

    /**
     * Sets the value of the miscFeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeIDType }
     *     
     */
    public void setMiscFeeID(MiscFeeIDType value) {
        this.miscFeeID = value;
    }

    /**
     * Gets the value of the miscFeeType property.
     * 
     * @return
     *     possible object is
     *     {@link MiscFeeTypeCode }
     *     
     */
    public MiscFeeTypeCode getMiscFeeType() {
        return miscFeeType;
    }

    /**
     * Sets the value of the miscFeeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiscFeeTypeCode }
     *     
     */
    public void setMiscFeeType(MiscFeeTypeCode value) {
        this.miscFeeType = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

}
