//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.13 at 11:38:26 AM EST 
//


package org.incomm.generated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExceptionResponseBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExceptionResponseBodyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.visa.com/ROLSI}ResponseBodyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="SubmitExceptionResponse" type="{http://www.visa.com/ROLSI}RTSIExceptionDetailsResponseType"/&gt;
 *           &lt;element name="ExceptionDetails" type="{http://www.visa.com/ROLSI}RTSIExceptionDetailsResponseType"/&gt;
 *           &lt;element name="InquiryExceptionResponse" type="{http://www.visa.com/ROLSI}RTSIExceptionDetailsResponseType"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExceptionResponseBodyType", propOrder = {
    "submitExceptionResponse",
    "exceptionDetails",
    "inquiryExceptionResponse"
})
public class ExceptionResponseBodyType
    extends ResponseBodyType
{

    @XmlElement(name = "SubmitExceptionResponse")
    protected RTSIExceptionDetailsResponseType submitExceptionResponse;
    @XmlElement(name = "ExceptionDetails")
    protected RTSIExceptionDetailsResponseType exceptionDetails;
    @XmlElement(name = "InquiryExceptionResponse")
    protected RTSIExceptionDetailsResponseType inquiryExceptionResponse;

    /**
     * Gets the value of the submitExceptionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public RTSIExceptionDetailsResponseType getSubmitExceptionResponse() {
        return submitExceptionResponse;
    }

    /**
     * Sets the value of the submitExceptionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public void setSubmitExceptionResponse(RTSIExceptionDetailsResponseType value) {
        this.submitExceptionResponse = value;
    }

    /**
     * Gets the value of the exceptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public RTSIExceptionDetailsResponseType getExceptionDetails() {
        return exceptionDetails;
    }

    /**
     * Sets the value of the exceptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public void setExceptionDetails(RTSIExceptionDetailsResponseType value) {
        this.exceptionDetails = value;
    }

    /**
     * Gets the value of the inquiryExceptionResponse property.
     * 
     * @return
     *     possible object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public RTSIExceptionDetailsResponseType getInquiryExceptionResponse() {
        return inquiryExceptionResponse;
    }

    /**
     * Sets the value of the inquiryExceptionResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTSIExceptionDetailsResponseType }
     *     
     */
    public void setInquiryExceptionResponse(RTSIExceptionDetailsResponseType value) {
        this.inquiryExceptionResponse = value;
    }

}
